# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# Generated by stubgen-pyx from python/pyarrow/_acero.pyx

import os
import re
import pyarrow
from typing import Any, Callable, IO, Iterable, Iterator, Literal, Mapping, NamedTuple, Self, Sequence
from pyarrow.lib import _Weakrefable
from _typeshed import Incomplete
from pyarrow._compute import Expression
from pyarrow.lib import *
from pyarrow.lib import RecordBatchReader, Table

class ExecNodeOptions(_Weakrefable):
    __slots__ = ()

class _TableSourceNodeOptions(ExecNodeOptions):

    def _set_options(self, table: Table) -> None:
        ...

class TableSourceNodeOptions(_TableSourceNodeOptions):

    def __init__(self, table: Table):
        ...

class _RecordBatchReaderSourceNodeOptions(ExecNodeOptions):

    def _set_options(self, reader: RecordBatchReader) -> None:
        ...

class RecordBatchReaderSourceNodeOptions(_RecordBatchReaderSourceNodeOptions):

    def __init__(self, reader: RecordBatchReader):
        ...

class _FilterNodeOptions(ExecNodeOptions):

    def _set_options(self, filter_expression: Expression) -> None:
        ...

class FilterNodeOptions(_FilterNodeOptions):

    def __init__(self, filter_expression: Expression):
        ...

class _ProjectNodeOptions(ExecNodeOptions):

    def _set_options(self, expressions, names=None) -> None:
        ...

class ProjectNodeOptions(_ProjectNodeOptions):

    def __init__(self, expressions, names=None):
        ...

class _AggregateNodeOptions(ExecNodeOptions):

    def _set_options(self, aggregates, keys=None) -> None:
        ...

class AggregateNodeOptions(_AggregateNodeOptions):

    def __init__(self, aggregates, keys=None):
        ...

class _OrderByNodeOptions(ExecNodeOptions):

    def _set_options(self, sort_keys, null_placement) -> None:
        ...

class OrderByNodeOptions(_OrderByNodeOptions):

    def __init__(self, sort_keys=(), *, null_placement=None):
        ...

class _HashJoinNodeOptions(ExecNodeOptions):

    def _set_options(self, join_type, left_keys, right_keys, left_output=None, right_output=None, output_suffix_for_left: str='', output_suffix_for_right: str='', filter_expression: Expression | None=None) -> None:
        ...

class HashJoinNodeOptions(_HashJoinNodeOptions):

    def __init__(self, join_type, left_keys, right_keys, left_output=None, right_output=None, output_suffix_for_left: str='', output_suffix_for_right: str='', filter_expression=None):
        ...

class _AsofJoinNodeOptions(ExecNodeOptions):

    def _set_options(self, left_on, left_by, right_on, right_by, tolerance) -> None:
        ...

class AsofJoinNodeOptions(_AsofJoinNodeOptions):

    def __init__(self, left_on, left_by, right_on, right_by, tolerance):
        ...

class Declaration(_Weakrefable):

    def __init__(self, factory_name, options: ExecNodeOptions, inputs=None):
        ...

    @staticmethod
    def from_sequence(decls: list[Declaration]) -> Declaration:
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self) -> str:
        ...

    def to_table(self, use_threads: bool=True) -> pyarrow.Table:
        ...

    def to_reader(self, use_threads: bool=True) -> pyarrow.RecordBatchReader:
        ...
