# This file was generated by stubgen-pyx v0.2.23 from python/pyarrow/_azurefs.pyx

from pyarrow._fs import FileSystem
from pyarrow.includes.libarrow_fs import *


class AzureFileSystem(FileSystem):
    def __init__(self, account_name, *, account_key=None, blob_storage_authority=None, blob_storage_scheme=None, client_id=None, client_secret=None, dfs_storage_authority=None, dfs_storage_scheme=None, sas_token=None, tenant_id=None): ...
    @staticmethod
    def _reconstruct(kwargs): ...
    def __reduce__(self): ...
