# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# Generated by stubgen-pyx from python/pyarrow/_azurefs.pyx

from pyarrow._fs import FileSystem

class AzureFileSystem(FileSystem):
    def __init__(
        self,
        account_name,
        *,
        account_key=None,
        blob_storage_authority=None,
        blob_storage_scheme=None,
        client_id=None,
        client_secret=None,
        dfs_storage_authority=None,
        dfs_storage_scheme=None,
        sas_token=None,
        tenant_id=None,
    ): ...
    @staticmethod
    def _reconstruct(kwargs) -> AzureFileSystem: ...
    def __reduce__(self) -> tuple: ...
