# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# Generated by stubgen-pyx from python/pyarrow/_compute.pyx

import os
import re
import pyarrow
from typing import IO, Iterable, Iterator, Literal, Mapping, NamedTuple, Self, Sequence
from pyarrow.lib import _Weakrefable
from _typeshed import Incomplete
from collections import namedtuple
from typing import Any, Callable
import pyarrow.lib as lib
from pyarrow.lib import *
from typing_extensions import TypeAlias
__pas: Incomplete
_substrait_msg: str
SUPPORTED_INPUT_ARR_TYPES: tuple[Incomplete, ...]
_deserialize: Incomplete

def _pas():
    ...

def _forbid_instantiation(klass, subclasses_instead: bool=True):
    ...

def function_registry():
    ...

def get_function(name: str):
    ...

def list_functions():
    ...

def call_function(name: str, args: list, options=None, memory_pool: pyarrow.MemoryPool | None=None, length: int | None=None):
    ...

def _raise_invalid_function_option(value, description, *, exception_class=ValueError):
    ...

def _skip_nulls_doc() -> str:
    ...

def _min_count_doc(*, default) -> str:
    ...

def _get_udf_context(memory_pool, batch_length):
    ...

def register_scalar_function(func: Callable[..., Any], function_name: str, function_doc: dict, in_types, out_type: pyarrow.DataType, func_registry: FunctionRegistry | None=None):
    ...

def register_vector_function(func: Callable[..., Any], function_name: str, function_doc: dict, in_types, out_type: pyarrow.DataType, func_registry: FunctionRegistry | None=None):
    ...

def register_aggregate_function(func: Callable[..., Any], function_name: str, function_doc: dict, in_types, out_type: pyarrow.DataType, func_registry: FunctionRegistry | None=None):
    ...

def register_tabular_function(func: Callable[..., Any], function_name: str, function_doc: dict, in_types, out_type, func_registry: FunctionRegistry | None=None):
    ...

def _register_user_defined_function(register_func, func: Callable[..., Any], function_name: str, function_doc: dict, in_types, out_type: pyarrow.DataType, func_registry: FunctionRegistry | None=None) -> None:
    ...

def call_tabular_function(function_name: str, args: Iterable[Any] | None=None, func_registry: FunctionRegistry | None=None) -> pyarrow.RecordBatchReader:
    ...

class FunctionDoc(NamedTuple):
    summary: Incomplete
    description: Incomplete
    arg_names: Incomplete
    options_class: Incomplete
    options_required: Incomplete

class Kernel(_Weakrefable):

    def __init__(self):
        ...

class ScalarKernel(Kernel):

    def __repr__(self) -> str:
        ...

class VectorKernel(Kernel):

    def __repr__(self) -> str:
        ...

class ScalarAggregateKernel(Kernel):

    def __repr__(self) -> str:
        ...

class HashAggregateKernel(Kernel):

    def __repr__(self) -> str:
        ...

class Function(_Weakrefable):
    _kind_map: Incomplete

    def __init__(self):
        ...

    def __repr__(self) -> str:
        ...

    def __reduce__(self) -> tuple:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def arity(self):
        ...

    @property
    def kind(self):
        ...

    @property
    def _doc(self):
        ...

    @property
    def num_kernels(self):
        ...

    def call(self, args: Iterable[Any], options: FunctionOptions | None=None, memory_pool: MemoryPool | None=None, length: int | None=None):
        ...

class ScalarFunction(Function):

    @property
    def kernels(self) -> list:
        ...

class VectorFunction(Function):

    @property
    def kernels(self) -> list:
        ...

class ScalarAggregateFunction(Function):

    @property
    def kernels(self) -> list:
        ...

class HashAggregateFunction(Function):

    @property
    def kernels(self) -> list:
        ...

class MetaFunction(Function):

    @property
    def kernels(self) -> list:
        ...

class FunctionRegistry(_Weakrefable):

    def __init__(self):
        ...

    def list_functions(self) -> list:
        ...

    def get_function(self, name: str):
        ...

class FunctionOptions(_Weakrefable):
    __slots__ = ()

    def serialize(self) -> pyarrow.Buffer:
        ...

    @staticmethod
    def deserialize(buf: Buffer):
        ...

    def __repr__(self) -> str:
        ...

    def __eq__(self, other: FunctionOptions):
        ...

class _CastOptions(FunctionOptions):

    def _set_options(self, target_type: DataType, allow_int_overflow, allow_time_truncate, allow_time_overflow, allow_decimal_truncate, allow_float_truncate, allow_invalid_utf8) -> None:
        ...

    def _set_type(self, target_type=None) -> None:
        ...

    def _set_safe(self) -> None:
        ...

    def _set_unsafe(self) -> None:
        ...

    def is_safe(self) -> bool:
        ...

    @property
    def allow_int_overflow(self) -> None:
        ...

    @allow_int_overflow.setter
    def allow_int_overflow(self, flag: bool) -> None:
        ...

    @property
    def allow_time_truncate(self) -> None:
        ...

    @allow_time_truncate.setter
    def allow_time_truncate(self, flag: bool) -> None:
        ...

    @property
    def allow_time_overflow(self) -> None:
        ...

    @allow_time_overflow.setter
    def allow_time_overflow(self, flag: bool) -> None:
        ...

    @property
    def allow_decimal_truncate(self) -> None:
        ...

    @allow_decimal_truncate.setter
    def allow_decimal_truncate(self, flag: bool) -> None:
        ...

    @property
    def allow_float_truncate(self) -> None:
        ...

    @allow_float_truncate.setter
    def allow_float_truncate(self, flag: bool) -> None:
        ...

    @property
    def allow_invalid_utf8(self) -> None:
        ...

    @allow_invalid_utf8.setter
    def allow_invalid_utf8(self, flag: bool) -> None:
        ...

class CastOptions(_CastOptions):

    def __init__(self, target_type=None, *, allow_int_overflow=None, allow_time_truncate=None, allow_time_overflow=None, allow_decimal_truncate=None, allow_float_truncate=None, allow_invalid_utf8=None):
        ...

    @staticmethod
    def safe(target_type=None) -> CastOptions:
        ...

    @staticmethod
    def unsafe(target_type=None) -> CastOptions:
        ...

class _ElementWiseAggregateOptions(FunctionOptions):

    def _set_options(self, skip_nulls) -> None:
        ...

class ElementWiseAggregateOptions(_ElementWiseAggregateOptions):

    def __init__(self, *, skip_nulls: bool=True):
        ...

class _RoundOptions(FunctionOptions):

    def _set_options(self, ndigits, round_mode) -> None:
        ...

class RoundOptions(_RoundOptions):

    def __init__(self, ndigits: int=0, round_mode: str='half_to_even'):
        ...

class _RoundBinaryOptions(FunctionOptions):

    def _set_options(self, round_mode) -> None:
        ...

class RoundBinaryOptions(_RoundBinaryOptions):

    def __init__(self, round_mode: str='half_to_even'):
        ...

class _RoundTemporalOptions(FunctionOptions):

    def _set_options(self, multiple, unit, week_starts_monday, ceil_is_strictly_greater, calendar_based_origin) -> None:
        ...

class RoundTemporalOptions(_RoundTemporalOptions):

    def __init__(self, multiple: int=1, unit: str='day', *, week_starts_monday: bool=True, ceil_is_strictly_greater: bool=False, calendar_based_origin: bool=False):
        ...

class _RoundToMultipleOptions(FunctionOptions):

    def _set_options(self, multiple, round_mode) -> None:
        ...

class RoundToMultipleOptions(_RoundToMultipleOptions):

    def __init__(self, multiple: float=1.0, round_mode: str='half_to_even'):
        ...

class _JoinOptions(FunctionOptions):
    _null_handling_map: Incomplete

    def _set_options(self, null_handling, null_replacement) -> None:
        ...

class JoinOptions(_JoinOptions):

    def __init__(self, null_handling: str='emit_null', null_replacement: str=''):
        ...

class _MatchSubstringOptions(FunctionOptions):

    def _set_options(self, pattern, ignore_case) -> None:
        ...

class MatchSubstringOptions(_MatchSubstringOptions):

    def __init__(self, pattern, *, ignore_case: bool=False):
        ...

class _PadOptions(FunctionOptions):

    def _set_options(self, width, padding, lean_left_on_odd_padding) -> None:
        ...

class PadOptions(_PadOptions):

    def __init__(self, width, padding: str=' ', lean_left_on_odd_padding: bool=True):
        ...

class _ZeroFillOptions(FunctionOptions):

    def _set_options(self, width, padding) -> None:
        ...

class ZeroFillOptions(_ZeroFillOptions):

    def __init__(self, width, padding: str='0'):
        ...

class _TrimOptions(FunctionOptions):

    def _set_options(self, characters) -> None:
        ...

class TrimOptions(_TrimOptions):

    def __init__(self, characters):
        ...

class _ReplaceSubstringOptions(FunctionOptions):

    def _set_options(self, pattern, replacement, max_replacements) -> None:
        ...

class ReplaceSubstringOptions(_ReplaceSubstringOptions):

    def __init__(self, pattern, replacement, *, max_replacements=None):
        ...

class _ExtractRegexOptions(FunctionOptions):

    def _set_options(self, pattern) -> None:
        ...

class ExtractRegexOptions(_ExtractRegexOptions):

    def __init__(self, pattern):
        ...

class _ExtractRegexSpanOptions(FunctionOptions):

    def _set_options(self, pattern) -> None:
        ...

class ExtractRegexSpanOptions(_ExtractRegexSpanOptions):

    def __init__(self, pattern):
        ...

class _SliceOptions(FunctionOptions):

    def _set_options(self, start, stop, step) -> None:
        ...

class SliceOptions(_SliceOptions):

    def __init__(self, start, stop=None, step: int=1):
        ...

class _ListSliceOptions(FunctionOptions):

    def _set_options(self, start, stop=None, step: int=1, return_fixed_size_list=None):
        ...

class ListSliceOptions(_ListSliceOptions):

    def __init__(self, start, stop=None, step: int=1, return_fixed_size_list=None):
        ...

class _ReplaceSliceOptions(FunctionOptions):

    def _set_options(self, start, stop, replacement) -> None:
        ...

class ReplaceSliceOptions(_ReplaceSliceOptions):

    def __init__(self, start, stop, replacement):
        ...

class _FilterOptions(FunctionOptions):
    _null_selection_map: Incomplete

    def _set_options(self, null_selection_behavior) -> None:
        ...

class FilterOptions(_FilterOptions):

    def __init__(self, null_selection_behavior: str='drop'):
        ...

class _DictionaryEncodeOptions(FunctionOptions):
    _null_encoding_map: Incomplete

    def _set_options(self, null_encoding) -> None:
        ...

class DictionaryEncodeOptions(_DictionaryEncodeOptions):

    def __init__(self, null_encoding: str='mask'):
        ...

class _RunEndEncodeOptions(FunctionOptions):

    def _set_options(self, run_end_type) -> None:
        ...

class RunEndEncodeOptions(_RunEndEncodeOptions):

    def __init__(self, run_end_type=lib.int32()):
        ...

class _InversePermutationOptions(FunctionOptions):

    def _set_options(self, max_index=-1, output_type=None) -> None:
        ...

class InversePermutationOptions(_InversePermutationOptions):

    def __init__(self, max_index=-1, output_type=None):
        ...

class _ScatterOptions(FunctionOptions):

    def _set_options(self, max_index) -> None:
        ...

class ScatterOptions(_ScatterOptions):

    def __init__(self, max_index=-1):
        ...

class _TakeOptions(FunctionOptions):

    def _set_options(self, boundscheck) -> None:
        ...

class TakeOptions(_TakeOptions):

    def __init__(self, *, boundscheck: bool=True):
        ...

class _MakeStructOptions(FunctionOptions):

    def _set_options(self, field_names, field_nullability, field_metadata) -> None:
        ...

class MakeStructOptions(_MakeStructOptions):

    def __init__(self, field_names=(), *, field_nullability=None, field_metadata=None):
        ...

class _StructFieldOptions(FunctionOptions):

    def _set_options(self, indices) -> None:
        ...

class StructFieldOptions(_StructFieldOptions):

    def __init__(self, indices):
        ...

class _ScalarAggregateOptions(FunctionOptions):

    def _set_options(self, skip_nulls, min_count) -> None:
        ...

class ScalarAggregateOptions(_ScalarAggregateOptions):

    def __init__(self, *, skip_nulls: bool=True, min_count: int=1):
        ...

class _CountOptions(FunctionOptions):
    _mode_map: Incomplete

    def _set_options(self, mode) -> None:
        ...

class CountOptions(_CountOptions):

    def __init__(self, mode: str='only_valid'):
        ...

class _IndexOptions(FunctionOptions):

    def _set_options(self, scalar) -> None:
        ...

class IndexOptions(_IndexOptions):

    def __init__(self, value):
        ...

class _MapLookupOptions(FunctionOptions):
    _occurrence_map: Incomplete

    def _set_options(self, query_key, occurrence) -> None:
        ...

class MapLookupOptions(_MapLookupOptions):

    def __init__(self, query_key, occurrence):
        ...

class _ModeOptions(FunctionOptions):

    def _set_options(self, n, skip_nulls, min_count) -> None:
        ...

class ModeOptions(_ModeOptions):

    def __init__(self, n: int=1, *, skip_nulls: bool=True, min_count: int=0):
        ...

class _SetLookupOptions(FunctionOptions):

    def _set_options(self, value_set, skip_nulls: bool) -> None:
        ...

class SetLookupOptions(_SetLookupOptions):

    def __init__(self, value_set, *, skip_nulls: bool=False):
        ...

class _StrptimeOptions(FunctionOptions):
    _unit_map: Incomplete

    def _set_options(self, format, unit, error_is_null) -> None:
        ...

class StrptimeOptions(_StrptimeOptions):

    def __init__(self, format, unit, error_is_null: bool=False):
        ...

class _StrftimeOptions(FunctionOptions):

    def _set_options(self, format, locale) -> None:
        ...

class StrftimeOptions(_StrftimeOptions):

    def __init__(self, format: str='%Y-%m-%dT%H:%M:%S', locale: str='C'):
        ...

class _DayOfWeekOptions(FunctionOptions):

    def _set_options(self, count_from_zero, week_start) -> None:
        ...

class DayOfWeekOptions(_DayOfWeekOptions):

    def __init__(self, *, count_from_zero: bool=True, week_start: int=1):
        ...

class _WeekOptions(FunctionOptions):

    def _set_options(self, week_starts_monday, count_from_zero, first_week_is_fully_in_year) -> None:
        ...

class WeekOptions(_WeekOptions):

    def __init__(self, *, week_starts_monday: bool=True, count_from_zero: bool=False, first_week_is_fully_in_year: bool=False):
        ...

class _AssumeTimezoneOptions(FunctionOptions):
    _ambiguous_map: Incomplete
    _nonexistent_map: Incomplete

    def _set_options(self, timezone, ambiguous, nonexistent) -> None:
        ...

class AssumeTimezoneOptions(_AssumeTimezoneOptions):

    def __init__(self, timezone, *, ambiguous: str='raise', nonexistent: str='raise'):
        ...

class _NullOptions(FunctionOptions):

    def _set_options(self, nan_is_null) -> None:
        ...

class NullOptions(_NullOptions):

    def __init__(self, *, nan_is_null: bool=False):
        ...

class _VarianceOptions(FunctionOptions):

    def _set_options(self, ddof, skip_nulls, min_count) -> None:
        ...

class VarianceOptions(_VarianceOptions):

    def __init__(self, *, ddof: int=0, skip_nulls: bool=True, min_count: int=0):
        ...

class _SkewOptions(FunctionOptions):

    def _set_options(self, skip_nulls, biased, min_count) -> None:
        ...

class SkewOptions(_SkewOptions):

    def __init__(self, *, skip_nulls: bool=True, biased: bool=True, min_count: int=0):
        ...

class _SplitOptions(FunctionOptions):

    def _set_options(self, max_splits, reverse) -> None:
        ...

class SplitOptions(_SplitOptions):

    def __init__(self, *, max_splits=None, reverse: bool=False):
        ...

class _SplitPatternOptions(FunctionOptions):

    def _set_options(self, pattern, max_splits, reverse) -> None:
        ...

class SplitPatternOptions(_SplitPatternOptions):

    def __init__(self, pattern, *, max_splits=None, reverse: bool=False):
        ...

class _PartitionNthOptions(FunctionOptions):

    def _set_options(self, pivot, null_placement) -> None:
        ...

class PartitionNthOptions(_PartitionNthOptions):

    def __init__(self, pivot, *, null_placement: str='at_end'):
        ...

class _WinsorizeOptions(FunctionOptions):

    def _set_options(self, lower_limit, upper_limit) -> None:
        ...

class WinsorizeOptions(_WinsorizeOptions):

    def __init__(self, lower_limit, upper_limit):
        ...

class _CumulativeOptions(FunctionOptions):

    def _set_options(self, start, skip_nulls) -> None:
        ...

class CumulativeOptions(_CumulativeOptions):

    def __init__(self, start=None, *, skip_nulls: bool=False):
        ...

class CumulativeSumOptions(_CumulativeOptions):

    def __init__(self, start=None, *, skip_nulls: bool=False):
        ...

class _PairwiseOptions(FunctionOptions):

    def _set_options(self, period) -> None:
        ...

class PairwiseOptions(_PairwiseOptions):

    def __init__(self, period: int=1):
        ...

class _ListFlattenOptions(FunctionOptions):

    def _set_options(self, recursive) -> None:
        ...

class ListFlattenOptions(_ListFlattenOptions):

    def __init__(self, recursive: bool=False):
        ...

class _ArraySortOptions(FunctionOptions):

    def _set_options(self, order, null_placement) -> None:
        ...

class ArraySortOptions(_ArraySortOptions):

    def __init__(self, order: str='ascending', *, null_placement: str='at_end'):
        ...

class _SearchSortedOptions(FunctionOptions):

    def _set_options(self, side) -> None:
        ...

class SearchSortedOptions(_SearchSortedOptions):

    def __init__(self, side: str='left'):
        ...

class _SortOptions(FunctionOptions):

    def _set_options(self, sort_keys, null_placement) -> None:
        ...

class SortOptions(_SortOptions):

    def __init__(self, sort_keys=(), *, null_placement=None):
        ...

class _SelectKOptions(FunctionOptions):

    def _set_options(self, k, sort_keys) -> None:
        ...

class SelectKOptions(_SelectKOptions):

    def __init__(self, k, sort_keys):
        ...

class _QuantileOptions(FunctionOptions):
    _interp_map: Incomplete

    def _set_options(self, quantiles, interp, skip_nulls, min_count) -> None:
        ...

class QuantileOptions(_QuantileOptions):

    def __init__(self, q: float=0.5, *, interpolation: str='linear', skip_nulls: bool=True, min_count: int=0):
        ...

class _TDigestOptions(FunctionOptions):

    def _set_options(self, quantiles, delta, buffer_size, skip_nulls, min_count) -> None:
        ...

class TDigestOptions(_TDigestOptions):

    def __init__(self, q: float=0.5, *, delta: int=100, buffer_size: int=500, skip_nulls: bool=True, min_count: int=0):
        ...

class _Utf8NormalizeOptions(FunctionOptions):
    _form_map: Incomplete

    def _set_options(self, form) -> None:
        ...

class Utf8NormalizeOptions(_Utf8NormalizeOptions):

    def __init__(self, form):
        ...

class _RandomOptions(FunctionOptions):

    def _set_options(self, initializer) -> None:
        ...

class RandomOptions(_RandomOptions):

    def __init__(self, *, initializer: str='system'):
        ...

class _RankOptions(FunctionOptions):
    _tiebreaker_map: Incomplete

    def _set_options(self, sort_keys, null_placement, tiebreaker) -> None:
        ...

class RankOptions(_RankOptions):

    def __init__(self, sort_keys: str='ascending', *, null_placement=None, tiebreaker: str='first'):
        ...

class _RankQuantileOptions(FunctionOptions):

    def _set_options(self, sort_keys, null_placement) -> None:
        ...

class RankQuantileOptions(_RankQuantileOptions):

    def __init__(self, sort_keys: str='ascending', *, null_placement=None):
        ...

class _PivotWiderOptions(FunctionOptions):

    def _set_options(self, key_names, unexpected_key_behavior) -> None:
        ...

class PivotWiderOptions(_PivotWiderOptions):

    def __init__(self, key_names, *, unexpected_key_behavior: str='ignore'):
        ...

class Expression(_Weakrefable):

    def __init__(self):
        ...

    def equals(self, other: Expression) -> bool:
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self) -> str:
        ...

    @staticmethod
    def from_substrait(message: object) -> Expression:
        ...

    def to_substrait(self, schema: Schema, allow_arrow_extensions: bool=False) -> pyarrow.Buffer:
        ...

    @staticmethod
    def _deserialize(buffer: Buffer) -> Expression:
        ...

    def __reduce__(self) -> tuple:
        ...

    @staticmethod
    def _call(function_name: str, arguments: list[Any], options: FunctionOptions | None=None) -> Expression:
        ...

    def __bool__(self):
        ...

    def __invert__(self):
        ...

    def __and__(self: Expression, other):
        ...

    def __rand__(self: Expression, other):
        ...

    def __or__(self: Expression, other):
        ...

    def __ror__(self: Expression, other):
        ...

    def __add__(self: Expression, other):
        ...

    def __radd__(self: Expression, other):
        ...

    def __mul__(self: Expression, other):
        ...

    def __rmul__(self: Expression, other):
        ...

    def __sub__(self: Expression, other):
        ...

    def __rsub__(self: Expression, other):
        ...

    def __truediv__(self: Expression, other):
        ...

    def __rtruediv__(self: Expression, other):
        ...

    def is_valid(self) -> Expression:
        ...

    def is_null(self, nan_is_null: bool=False) -> Expression:
        ...

    def is_nan(self) -> Expression:
        ...

    def cast(self, type: pyarrow.DataType | None=None, safe: bool | None=None, options: CastOptions | None=None) -> Expression:
        ...

    def isin(self, values: pyarrow.Array | Iterable[Any]) -> Expression:
        ...

    @staticmethod
    def _field(name_or_idx) -> Expression:
        ...

    @staticmethod
    def _nested_field(names: tuple[Any, ...]) -> Expression:
        ...

    @staticmethod
    def _scalar(value) -> Expression:
        ...

class UdfContext(_Weakrefable):

    def __init__(self):
        ...

    @property
    def batch_length(self):
        ...

    @property
    def memory_pool(self):
        ...

class RegisterUdf(_Weakrefable):
    ...
