# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# Generated by stubgen-pyx from python/pyarrow/_csv.pyx

import os
import re
import pyarrow
from typing import Any, Callable, IO, Iterable, Iterator, Literal, Mapping, NamedTuple, Self, Sequence
import pyarrow.csv
from pyarrow.lib import __name__ as __name__
from _typeshed import Incomplete
from collections import namedtuple
from pyarrow.lib import MemoryPool, RecordBatchReader, Schema, _CRecordBatchWriter, _Weakrefable
ISO8601: _ISO8601

def read_csv(input_file, read_options: pyarrow.csv.ReadOptions | None=None, parse_options: pyarrow.csv.ParseOptions | None=None, convert_options: pyarrow.csv.ConvertOptions | None=None, memory_pool: MemoryPool | None=None) -> pyarrow.Table:
    ...

def open_csv(input_file, read_options: pyarrow.csv.ReadOptions | None=None, parse_options: pyarrow.csv.ParseOptions | None=None, convert_options: pyarrow.csv.ConvertOptions | None=None, memory_pool: MemoryPool | None=None) -> CSVStreamingReader:
    ...

def _raise_invalid_function_option(value, description, *, exception_class=ValueError):
    ...

def write_csv(data: pyarrow.RecordBatch | pyarrow.Table, output_file, write_options: pyarrow.csv.WriteOptions | None=None, memory_pool: MemoryPool | None=None) -> None:
    ...

class _InvalidRow(NamedTuple):
    expected_columns: Incomplete
    actual_columns: Incomplete
    number: Incomplete
    text: Incomplete

class InvalidRow(_InvalidRow):
    __slots__ = ()

class ReadOptions(_Weakrefable):
    __slots__ = ()
    encoding: object

    def __init__(self, *, use_threads=None, block_size=None, skip_rows=None, skip_rows_after_names=None, column_names=None, autogenerate_column_names=None, encoding: str='utf8'):
        ...

    @property
    def use_threads(self) -> None:
        ...

    @use_threads.setter
    def use_threads(self, value) -> None:
        ...

    @property
    def block_size(self) -> None:
        ...

    @block_size.setter
    def block_size(self, value) -> None:
        ...

    @property
    def skip_rows(self) -> None:
        ...

    @skip_rows.setter
    def skip_rows(self, value) -> None:
        ...

    @property
    def skip_rows_after_names(self) -> None:
        ...

    @skip_rows_after_names.setter
    def skip_rows_after_names(self, value) -> None:
        ...

    @property
    def column_names(self) -> None:
        ...

    @column_names.setter
    def column_names(self, value) -> None:
        ...

    @property
    def autogenerate_column_names(self) -> None:
        ...

    @autogenerate_column_names.setter
    def autogenerate_column_names(self, value) -> None:
        ...

    def validate(self) -> None:
        ...

    def equals(self, other: ReadOptions) -> bool:
        ...

    def __getstate__(self) -> tuple:
        ...

    def __setstate__(self, state) -> None:
        ...

    def __eq__(self, other):
        ...

    def _repr_base(self) -> str:
        ...

    def __repr__(self) -> str:
        ...

    def __str__(self) -> str:
        ...

class ParseOptions(_Weakrefable):
    __slots__ = ()

    def __init__(self, *, delimiter=None, quote_char=None, double_quote=None, escape_char=None, newlines_in_values=None, ignore_empty_lines=None, invalid_row_handler=None):
        ...

    @property
    def delimiter(self) -> None:
        ...

    @delimiter.setter
    def delimiter(self, value) -> None:
        ...

    @property
    def quote_char(self) -> None:
        ...

    @quote_char.setter
    def quote_char(self, value) -> None:
        ...

    @property
    def double_quote(self) -> None:
        ...

    @double_quote.setter
    def double_quote(self, value) -> None:
        ...

    @property
    def escape_char(self) -> None:
        ...

    @escape_char.setter
    def escape_char(self, value) -> None:
        ...

    @property
    def newlines_in_values(self) -> None:
        ...

    @newlines_in_values.setter
    def newlines_in_values(self, value) -> None:
        ...

    @property
    def ignore_empty_lines(self) -> None:
        ...

    @property
    def invalid_row_handler(self) -> None:
        ...

    @invalid_row_handler.setter
    def invalid_row_handler(self, value) -> None:
        ...

    @ignore_empty_lines.setter
    def ignore_empty_lines(self, value) -> None:
        ...

    def validate(self) -> None:
        ...

    def equals(self, other: ParseOptions) -> bool:
        ...

    def __getstate__(self) -> tuple:
        ...

    def __setstate__(self, state) -> None:
        ...

    def __eq__(self, other):
        ...

    def _repr_base(self) -> str:
        ...

    def __repr__(self) -> str:
        ...

    def __str__(self) -> str:
        ...

class _ISO8601(_Weakrefable):
    __slots__ = ()

    def __str__(self) -> str:
        ...

    def __eq__(self, other) -> bool:
        ...

class ConvertOptions(_Weakrefable):
    __slots__ = ()

    def __init__(self, *, check_utf8=None, column_types=None, default_column_type=None, null_values=None, true_values=None, false_values=None, decimal_point=None, strings_can_be_null=None, quoted_strings_can_be_null=None, include_columns=None, include_missing_columns=None, auto_dict_encode=None, auto_dict_max_cardinality=None, timestamp_parsers=None):
        ...

    @property
    def check_utf8(self) -> None:
        ...

    @check_utf8.setter
    def check_utf8(self, value) -> None:
        ...

    @property
    def strings_can_be_null(self) -> None:
        ...

    @strings_can_be_null.setter
    def strings_can_be_null(self, value) -> None:
        ...

    @property
    def quoted_strings_can_be_null(self) -> None:
        ...

    @quoted_strings_can_be_null.setter
    def quoted_strings_can_be_null(self, value) -> None:
        ...

    @property
    def column_types(self) -> None:
        ...

    @column_types.setter
    def column_types(self, value) -> None:
        ...

    @property
    def default_column_type(self) -> None:
        ...

    @default_column_type.setter
    def default_column_type(self, value) -> None:
        ...

    @property
    def null_values(self) -> None:
        ...

    @null_values.setter
    def null_values(self, value) -> None:
        ...

    @property
    def true_values(self) -> None:
        ...

    @true_values.setter
    def true_values(self, value) -> None:
        ...

    @property
    def false_values(self) -> None:
        ...

    @false_values.setter
    def false_values(self, value) -> None:
        ...

    @property
    def decimal_point(self) -> None:
        ...

    @decimal_point.setter
    def decimal_point(self, value) -> None:
        ...

    @property
    def auto_dict_encode(self) -> None:
        ...

    @auto_dict_encode.setter
    def auto_dict_encode(self, value) -> None:
        ...

    @property
    def auto_dict_max_cardinality(self) -> None:
        ...

    @auto_dict_max_cardinality.setter
    def auto_dict_max_cardinality(self, value) -> None:
        ...

    @property
    def include_columns(self) -> None:
        ...

    @include_columns.setter
    def include_columns(self, value) -> None:
        ...

    @property
    def include_missing_columns(self) -> None:
        ...

    @include_missing_columns.setter
    def include_missing_columns(self, value) -> None:
        ...

    @property
    def timestamp_parsers(self) -> None:
        ...

    @timestamp_parsers.setter
    def timestamp_parsers(self, value) -> None:
        ...

    def validate(self) -> None:
        ...

    def equals(self, other: ConvertOptions) -> bool:
        ...

    def __getstate__(self) -> tuple:
        ...

    def __setstate__(self, state) -> None:
        ...

    def __eq__(self, other):
        ...

    def _repr_base(self) -> str:
        ...

    def __repr__(self) -> str:
        ...

    def __str__(self) -> str:
        ...

class CSVStreamingReader(RecordBatchReader):
    schema: Schema

    def __init__(self):
        ...

class WriteOptions(_Weakrefable):
    __slots__ = ()

    def __init__(self, *, include_header=None, batch_size=None, delimiter=None, eol=None, null_string=None, quoting_style=None, quoting_header=None):
        ...

    @property
    def include_header(self) -> None:
        ...

    @include_header.setter
    def include_header(self, value) -> None:
        ...

    @property
    def batch_size(self) -> None:
        ...

    @batch_size.setter
    def batch_size(self, value) -> None:
        ...

    @property
    def delimiter(self) -> None:
        ...

    @delimiter.setter
    def delimiter(self, value) -> None:
        ...

    @property
    def eol(self) -> None:
        ...

    @eol.setter
    def eol(self, value) -> None:
        ...

    @property
    def null_string(self) -> None:
        ...

    @null_string.setter
    def null_string(self, value) -> None:
        ...

    @property
    def quoting_style(self) -> None:
        ...

    @quoting_style.setter
    def quoting_style(self, value) -> None:
        ...

    @property
    def quoting_header(self) -> None:
        ...

    @quoting_header.setter
    def quoting_header(self, value) -> None:
        ...

    def validate(self) -> None:
        ...

    def _repr_base(self) -> str:
        ...

    def __repr__(self) -> str:
        ...

    def __str__(self) -> str:
        ...

class CSVWriter(_CRecordBatchWriter):

    def __init__(self, sink, schema: Schema, *, write_options: WriteOptions | None=None, memory_pool: MemoryPool | None=None):
        ...
