# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# Generated by stubgen-pyx from python/pyarrow/_feather.pyx

import os
import re
import pyarrow
from typing import Any, Callable, IO, Iterable, Iterator, Literal, Mapping, NamedTuple, Self, Sequence
from _typeshed import Incomplete
from pyarrow.lib import Table, _Weakrefable

def write_feather(table: Table, dest: object, compression=None, compression_level=None, chunksize=None, version: int=2) -> None:
    ...

class FeatherError(Exception):
    ...

class FeatherReader(_Weakrefable):

    def __init__(self, source, use_memory_map: bool, use_threads: bool):
        ...

    @property
    def version(self):
        ...

    def read(self) -> pyarrow.Table:
        ...

    def read_indices(self, indices) -> pyarrow.Table:
        ...

    def read_names(self, names) -> pyarrow.Table:
        ...
