# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Generated by stubgen-pyx from python/pyarrow/_feather.pyx
from _typeshed import Incomplete

from pyarrow.includes.common import *
from pyarrow.includes.libarrow import *
from pyarrow.includes.libarrow_feather import *
from pyarrow.lib import Table, _Weakrefable


class FeatherError(Exception): ...

class FeatherReader(_Weakrefable):
    def __init__(self, source, use_memory_map: c_bool, use_threads: c_bool): ...
    @property
    def version(self): ...
    def read(self): ...
    def read_indices(self, indices): ...
    def read_names(self, names): ...

def write_feather(table: Table, dest: object, compression=None, compression_level=None, chunksize=None, version=2): ...
