# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# Generated by stubgen-pyx from python/pyarrow/_gcsfs.pyx

from pyarrow._fs import FileSystem

class GcsFileSystem(FileSystem):
    def __init__(
        self,
        *,
        anonymous: bool = False,
        access_token=None,
        target_service_account=None,
        credential_token_expiration=None,
        default_bucket_location: str = "US",
        scheme=None,
        endpoint_override=None,
        default_metadata=None,
        retry_time_limit=None,
        project_id=None,
    ): ...
    def _expiration_datetime_from_options(self): ...
    @staticmethod
    def _reconstruct(kwargs) -> GcsFileSystem: ...
    def __reduce__(self) -> tuple: ...
    @property
    def default_bucket_location(self) -> str: ...
    @property
    def project_id(self) -> str: ...
