# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Generated by stubgen-pyx from python/pyarrow/_hdfs.pyx
from _typeshed import Incomplete

from pyarrow._fs import FileSystem
from pyarrow.includes.common import *
from pyarrow.includes.libarrow import *
from pyarrow.includes.libarrow_fs import *


class HadoopFileSystem(FileSystem):
    def __init__(self, host: str, port: int=8020, *, user: str | None=None, replication: int=3, buffer_size: int=0, default_block_size=None, kerb_ticket=None, extra_conf=None): ...
    @staticmethod
    def from_uri(uri): ...
    @staticmethod
    def _reconstruct(kwargs): ...
    def __reduce__(self): ...

def _have_libhdfs(): ...
