# This file was generated by stubgen-pyx v0.2.23 from python/pyarrow/_hdfs.pyx

from pyarrow._fs import FileSystem
from pyarrow.includes.common import *
from pyarrow.includes.libarrow import *
from pyarrow.includes.libarrow_fs import *


class HadoopFileSystem(FileSystem):
    def __init__(self, host: str, port: int=8020, *, user: str | None=None, replication: int=3, buffer_size: int=0, default_block_size=None, kerb_ticket=None, extra_conf=None): ...
    @staticmethod
    def from_uri(uri): ...
    @staticmethod
    def _reconstruct(kwargs): ...
    def __reduce__(self): ...

def _have_libhdfs(): ...
