# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# Generated by stubgen-pyx from python/pyarrow/_json.pyx

import pyarrow
import pyarrow.json
from pyarrow.lib import MemoryPool, RecordBatchReader, Schema, _Weakrefable

def read_json(
    input_file,
    read_options: pyarrow.json.ReadOptions | None = None,
    parse_options: pyarrow.json.ParseOptions | None = None,
    memory_pool: MemoryPool | None = None,
) -> pyarrow.Table: ...
def open_json(
    input_file,
    read_options: pyarrow.json.ReadOptions | None = None,
    parse_options: pyarrow.json.ParseOptions | None = None,
    memory_pool: MemoryPool | None = None,
) -> JSONStreamingReader: ...

class ReadOptions(_Weakrefable):
    __slots__ = ()

    def __init__(self, use_threads=None, block_size=None): ...
    @property
    def use_threads(self) -> None: ...
    @use_threads.setter
    def use_threads(self, value) -> None: ...
    @property
    def block_size(self) -> None: ...
    @block_size.setter
    def block_size(self, value) -> None: ...
    def __reduce__(self) -> tuple: ...
    def equals(self, other: ReadOptions) -> bool: ...
    def __eq__(self, other): ...

class ParseOptions(_Weakrefable):
    __slots__ = ()

    def __init__(
        self,
        explicit_schema=None,
        newlines_in_values=None,
        unexpected_field_behavior=None,
    ): ...
    def __reduce__(self) -> tuple: ...
    @property
    def explicit_schema(self) -> None: ...
    @explicit_schema.setter
    def explicit_schema(self, value) -> None: ...
    @property
    def newlines_in_values(self) -> None: ...
    @newlines_in_values.setter
    def newlines_in_values(self, value) -> None: ...
    @property
    def unexpected_field_behavior(self) -> None: ...
    @unexpected_field_behavior.setter
    def unexpected_field_behavior(self, value) -> None: ...
    def equals(self, other: ParseOptions) -> bool: ...
    def __eq__(self, other): ...
    def _repr_base(self) -> str: ...

class JSONStreamingReader(RecordBatchReader):
    schema: Schema

    def __init__(self): ...
