# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# Generated by stubgen-pyx from python/pyarrow/_parquet_encryption.pyx

import pyarrow
import pyarrow.parquet
from typing import Any
from pyarrow._fs import FileSystem
from pyarrow.lib import _Weakrefable

def create_decryption_properties(
    footer_key: bytes,
    *,
    aad_prefix: bytes | None = None,
    check_footer_integrity: bool = True,
    allow_plaintext_files: bool = False,
) -> pyarrow.parquet.FileDecryptionProperties: ...
def create_encryption_properties(
    footer_key: bytes,
    *,
    aad_prefix: bytes | None = None,
    store_aad_prefix: bool = True,
    encryption_algorithm: str = "AES_GCM_V1",
    plaintext_footer: bool = False,
) -> pyarrow.parquet.FileEncryptionProperties: ...

class EncryptionConfiguration(_Weakrefable):
    __slots__ = ()

    def __init__(
        self,
        footer_key,
        *,
        column_keys=None,
        uniform_encryption=None,
        encryption_algorithm=None,
        plaintext_footer=None,
        double_wrapping=None,
        cache_lifetime=None,
        internal_key_material=None,
        data_key_length_bits=None,
    ): ...
    @property
    def footer_key(self) -> str: ...
    @property
    def column_keys(self) -> None: ...
    @column_keys.setter
    def column_keys(self, value: dict[Any, Any]) -> None: ...
    @property
    def uniform_encryption(self) -> None: ...
    @uniform_encryption.setter
    def uniform_encryption(self, value) -> None: ...
    @property
    def encryption_algorithm(self) -> None: ...
    @encryption_algorithm.setter
    def encryption_algorithm(self, value) -> None: ...
    @property
    def plaintext_footer(self) -> None: ...
    @plaintext_footer.setter
    def plaintext_footer(self, value) -> None: ...
    @property
    def double_wrapping(self) -> None: ...
    @double_wrapping.setter
    def double_wrapping(self, value) -> None: ...
    @property
    def cache_lifetime(self) -> None: ...
    @cache_lifetime.setter
    def cache_lifetime(self, value) -> None: ...
    @property
    def internal_key_material(self) -> None: ...
    @internal_key_material.setter
    def internal_key_material(self, value) -> None: ...
    @property
    def data_key_length_bits(self) -> None: ...
    @data_key_length_bits.setter
    def data_key_length_bits(self, value) -> None: ...

class DecryptionConfiguration(_Weakrefable):
    __slots__ = ()

    def __init__(self, *, cache_lifetime=None, read_kms_url=None): ...
    @property
    def cache_lifetime(self) -> None: ...
    @cache_lifetime.setter
    def cache_lifetime(self, value) -> None: ...
    @property
    def read_kms_url(self) -> None: ...
    @read_kms_url.setter
    def read_kms_url(self, value) -> None: ...

class KmsConnectionConfig(_Weakrefable):
    __slots__ = ()

    def __init__(
        self,
        *,
        kms_instance_id=None,
        kms_instance_url=None,
        key_access_token=None,
        custom_kms_conf=None,
    ): ...
    @property
    def kms_instance_id(self) -> None: ...
    @kms_instance_id.setter
    def kms_instance_id(self, value) -> None: ...
    @property
    def kms_instance_url(self) -> None: ...
    @kms_instance_url.setter
    def kms_instance_url(self, value) -> None: ...
    @property
    def key_access_token(self) -> None: ...
    @key_access_token.setter
    def key_access_token(self, value) -> None: ...
    @property
    def custom_kms_conf(self) -> None: ...
    @custom_kms_conf.setter
    def custom_kms_conf(self, value: dict[Any, Any]) -> None: ...
    def refresh_key_access_token(self, value) -> None: ...

class KmsClient(_Weakrefable):
    def __init__(self): ...
    def wrap_key(self, key_bytes, master_key_identifier): ...
    def unwrap_key(self, wrapped_key, master_key_identifier): ...

class CryptoFactory(_Weakrefable):
    __slots__ = ()

    def __init__(self, kms_client_factory): ...
    def file_encryption_properties(
        self,
        kms_connection_config: KmsConnectionConfig,
        encryption_config: EncryptionConfiguration,
        parquet_file_path=None,
        filesystem: FileSystem | None = None,
    ) -> pyarrow.parquet.FileEncryptionProperties: ...
    def file_decryption_properties(
        self,
        kms_connection_config: KmsConnectionConfig,
        decryption_config: DecryptionConfiguration | None = None,
        parquet_file_path=None,
        filesystem: FileSystem | None = None,
    ) -> pyarrow.parquet.FileDecryptionProperties: ...
    def remove_cache_entries_for_token(self, access_token) -> None: ...
    def remove_cache_entries_for_all_tokens(self) -> None: ...
    def rotate_master_keys(
        self,
        kms_connection_config: KmsConnectionConfig,
        parquet_file_path,
        filesystem: FileSystem | None = None,
        double_wrapping: bool = True,
        cache_lifetime_seconds: float = 600,
        read_kms_url: bool = False,
    ) -> None: ...

class KeyMaterial(_Weakrefable):
    @property
    def is_footer_key(self): ...
    @property
    def is_double_wrapped(self): ...
    @property
    def master_key_id(self) -> str: ...
    @property
    def wrapped_dek(self) -> str: ...
    @property
    def kek_id(self) -> str: ...
    @property
    def wrapped_kek(self) -> str: ...
    @property
    def kms_instance_id(self) -> str: ...
    @property
    def kms_instance_url(self) -> str: ...
    @staticmethod
    def parse(key_material_string: bytes) -> KeyMaterial: ...

class FileSystemKeyMaterialStore(_Weakrefable):
    def get_key_material(self, key_id): ...
    def get_key_id_set(self): ...
    @classmethod
    def for_file(
        cls, parquet_file_path, filesystem: FileSystem | None = None
    ) -> FileSystemKeyMaterialStore: ...
