# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# Generated by stubgen-pyx from python/pyarrow/_parquet.pyx

import os
import re
import pyarrow
from typing import Callable, IO, Iterable, Iterator, Literal, Mapping, NamedTuple, Self, Sequence
from _typeshed import Incomplete
from typing import Any
from pyarrow.lib import Buffer, MemoryPool, Schema, Table, _Weakrefable
_DEFAULT_ROW_GROUP_SIZE: int
_MAX_ROW_GROUP_SIZE: int

def _reconstruct_filemetadata(serialized: Buffer) -> FileMetaData:
    ...

class Statistics(_Weakrefable):

    def __init__(self):
        ...

    def __repr__(self) -> str:
        ...

    def to_dict(self) -> dict:
        ...

    def __eq__(self, other):
        ...

    def equals(self, other: Statistics) -> bool:
        ...

    @property
    def has_min_max(self):
        ...

    @property
    def has_null_count(self):
        ...

    @property
    def has_distinct_count(self):
        ...

    @property
    def min_raw(self):
        ...

    @property
    def max_raw(self):
        ...

    @property
    def min(self):
        ...

    @property
    def max(self):
        ...

    @property
    def null_count(self):
        ...

    @property
    def distinct_count(self):
        ...

    @property
    def num_values(self):
        ...

    @property
    def physical_type(self):
        ...

    @property
    def logical_type(self):
        ...

    @property
    def converted_type(self):
        ...

class ParquetLogicalType(_Weakrefable):

    def __init__(self):
        ...

    def __repr__(self) -> str:
        ...

    def __str__(self) -> str:
        ...

    def to_json(self) -> str:
        ...

    @property
    def type(self):
        ...

class GeoStatistics(_Weakrefable):

    def __init__(self):
        ...

    def __repr__(self) -> str:
        ...

    def to_dict(self) -> dict:
        ...

    @property
    def geospatial_types(self) -> None | list:
        ...

    @property
    def xmin(self):
        ...

    @property
    def xmax(self):
        ...

    @property
    def ymin(self):
        ...

    @property
    def ymax(self):
        ...

    @property
    def zmin(self):
        ...

    @property
    def zmax(self):
        ...

    @property
    def mmin(self):
        ...

    @property
    def mmax(self):
        ...

    def _x_valid(self):
        ...

    def _y_valid(self):
        ...

    def _z_valid(self):
        ...

    def _m_valid(self):
        ...

class ColumnChunkMetaData(_Weakrefable):

    def __init__(self):
        ...

    def __repr__(self) -> str:
        ...

    def to_dict(self) -> dict:
        ...

    def __eq__(self, other):
        ...

    def equals(self, other: ColumnChunkMetaData) -> bool:
        ...

    @property
    def file_offset(self):
        ...

    @property
    def file_path(self) -> str:
        ...

    @property
    def physical_type(self):
        ...

    @property
    def num_values(self):
        ...

    @property
    def path_in_schema(self) -> str:
        ...

    @property
    def is_stats_set(self):
        ...

    @property
    def statistics(self) -> None | Statistics:
        ...

    @property
    def is_geo_stats_set(self):
        ...

    @property
    def geo_statistics(self) -> None | GeoStatistics:
        ...

    @property
    def compression(self):
        ...

    @property
    def encodings(self) -> tuple:
        ...

    @property
    def has_dictionary_page(self) -> bool:
        ...

    @property
    def dictionary_page_offset(self):
        ...

    @property
    def data_page_offset(self):
        ...

    @property
    def has_index_page(self):
        ...

    @property
    def index_page_offset(self):
        ...

    @property
    def total_compressed_size(self):
        ...

    @property
    def total_uncompressed_size(self):
        ...

    @property
    def bloom_filter_offset(self):
        ...

    @property
    def bloom_filter_length(self):
        ...

    @property
    def has_offset_index(self):
        ...

    @property
    def has_column_index(self):
        ...

    @property
    def metadata(self):
        ...

class SortingColumn:

    def __init__(self, column_index: int, descending: bool=False, nulls_first: bool=False):
        ...

    @classmethod
    def from_ordering(cls, schema: Schema, sort_keys, null_placement: str='at_end') -> tuple:
        ...

    @staticmethod
    def to_ordering(schema: Schema, sorting_columns: tuple[SortingColumn, ...]) -> tuple:
        ...

    def __repr__(self) -> str:
        ...

    def __eq__(self, other: SortingColumn):
        ...

    def __hash__(self):
        ...

    @property
    def column_index(self):
        ...

    @property
    def descending(self):
        ...

    @property
    def nulls_first(self):
        ...

    def to_dict(self) -> dict:
        ...

class RowGroupMetaData(_Weakrefable):

    def __init__(self):
        ...

    def __reduce__(self) -> tuple:
        ...

    def __eq__(self, other):
        ...

    def equals(self, other: RowGroupMetaData) -> bool:
        ...

    def column(self, i: int) -> ColumnChunkMetaData:
        ...

    def __repr__(self) -> str:
        ...

    def to_dict(self) -> dict:
        ...

    @property
    def num_columns(self):
        ...

    @property
    def num_rows(self):
        ...

    @property
    def total_byte_size(self):
        ...

    @property
    def sorting_columns(self) -> tuple:
        ...

class FileMetaData(_Weakrefable):

    def __init__(self):
        ...

    def __reduce__(self) -> tuple:
        ...

    def __hash__(self):
        ...

    def __repr__(self) -> str:
        ...

    def to_dict(self) -> dict:
        ...

    def __eq__(self, other):
        ...

    def equals(self, other: FileMetaData) -> bool:
        ...

    @property
    def schema(self):
        ...

    @property
    def serialized_size(self):
        ...

    @property
    def num_columns(self):
        ...

    @property
    def num_rows(self):
        ...

    @property
    def num_row_groups(self):
        ...

    @property
    def format_version(self) -> str:
        ...

    @property
    def created_by(self) -> str:
        ...

    @property
    def metadata(self):
        ...

    def row_group(self, i: int) -> RowGroupMetaData:
        ...

    def set_file_path(self, path: str) -> None:
        ...

    def append_row_groups(self, other: FileMetaData) -> None:
        ...

    def write_metadata_file(self, where) -> None:
        ...

class ParquetSchema(_Weakrefable):

    def __init__(self, container: FileMetaData):
        ...

    def __repr__(self) -> str:
        ...

    def __reduce__(self) -> tuple:
        ...

    def __len__(self):
        ...

    def __getitem__(self, i):
        ...

    def __hash__(self):
        ...

    @property
    def names(self) -> list:
        ...

    def to_arrow_schema(self) -> pyarrow.Schema:
        ...

    def __eq__(self, other):
        ...

    def equals(self, other: ParquetSchema) -> bool:
        ...

    def column(self, i: int) -> ColumnSchema:
        ...

class ColumnSchema(_Weakrefable):

    def __init__(self, schema: ParquetSchema, index: int):
        ...

    def __eq__(self, other):
        ...

    def __reduce__(self) -> tuple:
        ...

    def equals(self, other: ColumnSchema) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def path(self) -> str:
        ...

    @property
    def max_definition_level(self):
        ...

    @property
    def max_repetition_level(self):
        ...

    @property
    def physical_type(self):
        ...

    @property
    def logical_type(self):
        ...

    @property
    def converted_type(self):
        ...

    @property
    def length(self):
        ...

    @property
    def precision(self):
        ...

    @property
    def scale(self):
        ...

class ParquetReader(_Weakrefable):
    _column_idx_map: Any

    def __init__(self, memory_pool: MemoryPool | None=None):
        ...

    def open(self, source: object, *, use_memory_map: bool=False, read_dictionary=None, binary_type: pyarrow.DataType | None=None, list_type=None, metadata: FileMetaData | None=None, buffer_size: int=0, pre_buffer: bool=True, coerce_int96_timestamp_unit: str | None=None, decryption_properties: FileDecryptionProperties | None=None, thrift_string_size_limit: int | None=None, thrift_container_size_limit: int | None=None, schema_depth_limit: int | None=None, page_checksum_verification: bool=False, arrow_extensions_enabled: bool=False) -> None:
        ...

    @property
    def column_paths(self) -> list:
        ...

    @property
    def metadata(self):
        ...

    @property
    def schema_arrow(self) -> pyarrow.Schema:
        ...

    @property
    def num_row_groups(self):
        ...

    def set_use_threads(self, use_threads: bool) -> None:
        ...

    def set_batch_size(self, batch_size: int) -> None:
        ...

    def iter_batches(self, batch_size: int, row_groups: list[int], column_indices: list[int] | None=None, use_threads: bool=True) -> Iterator[pyarrow.RecordBatch]:
        ...

    def read_row_group(self, i: int, column_indices: list[int] | None=None, use_threads: bool=True) -> pyarrow.Table:
        ...

    def read_row_groups(self, row_groups: list[int], column_indices: list[int] | None=None, use_threads: bool=True) -> pyarrow.Table:
        ...

    def read_all(self, column_indices: list[int] | None=None, use_threads: bool=True) -> pyarrow.Table:
        ...

    def scan_contents(self, column_indices: list[int] | None=None, batch_size: int=65536) -> int:
        ...

    def column_name_idx(self, column_name: str) -> int:
        ...

    def read_column(self, column_index: int) -> pyarrow.ChunkedArray:
        ...

    def close(self) -> None:
        ...

    @property
    def closed(self):
        ...

class ParquetWriter(_Weakrefable):

    def __init__(self, where, schema: Schema, use_dictionary=None, compression=None, version=None, write_statistics=None, memory_pool: MemoryPool | None=None, use_deprecated_int96_timestamps: bool=False, coerce_timestamps=None, data_page_size=None, max_rows_per_page=None, allow_truncated_timestamps: bool=False, compression_level=None, use_byte_stream_split: bool=False, column_encoding=None, writer_engine_version=None, data_page_version=None, use_compliant_nested_type: bool=True, encryption_properties=None, write_batch_size=None, dictionary_pagesize_limit=None, store_schema: bool=True, write_page_index: bool=False, write_page_checksum: bool=False, sorting_columns=None, store_decimal_as_integer: bool=False, use_content_defined_chunking: bool=False, write_time_adjusted_to_utc: bool=False, bloom_filter_options=None):
        ...

    def close(self) -> None:
        ...

    def write_table(self, table: Table, row_group_size=None) -> None:
        ...

    def add_key_value_metadata(self, key_value_metadata) -> None:
        ...

    @property
    def metadata(self) -> FileMetaData:
        ...

class FileEncryptionProperties:
    ...

class FileDecryptionProperties:
    ...
