# Generated by stubgen-pyx from python/pyarrow/_pyarrow_cpp_tests.pyx
from _typeshed import Incomplete

from typing import Callable

from _typeshed import Incomplete
from pyarrow.includes.common import *
from pyarrow.includes.libarrow import *
from pyarrow.includes.libarrow import CStatus
from typing_extensions import TypeAlias


class CppTestCase:
    @property
    def name(self): ...
    def __repr__(self): ...
    def __call__(self): ...

def get_cpp_tests(): ...
