# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Generated by stubgen-pyx from python/pyarrow/_pyarrow_cpp_tests.pyx
from _typeshed import Incomplete

from typing import Callable

from _typeshed import Incomplete
from pyarrow.includes.common import *
from pyarrow.includes.libarrow import *
from pyarrow.includes.libarrow import CStatus
from typing_extensions import TypeAlias


class CppTestCase:
    @property
    def name(self): ...
    def __repr__(self): ...
    def __call__(self): ...

def get_cpp_tests(): ...
