# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# Generated by stubgen-pyx from python/pyarrow/_s3fs.pyx

import os
import re
import pyarrow
from typing import Any, Callable, IO, Iterable, Iterator, Literal, Mapping, NamedTuple, Self, Sequence
from _typeshed import Incomplete
from enum import IntEnum
from pyarrow._fs import FileSystem

def initialize_s3(log_level: S3LogLevel=S3LogLevel.Fatal, num_event_loop_threads: int=1) -> None:
    ...

def ensure_s3_initialized() -> None:
    ...

def finalize_s3() -> None:
    ...

def ensure_s3_finalized() -> None:
    ...

def resolve_s3_region(bucket: str) -> str:
    ...

class S3LogLevel(IntEnum):
    Off = ...
    Fatal = ...
    Error = ...
    Warn = ...
    Info = ...
    Debug = ...
    Trace = ...

class S3RetryStrategy:

    def __init__(self, max_attempts: int=3):
        ...

class AwsStandardS3RetryStrategy(S3RetryStrategy):
    ...

class AwsDefaultS3RetryStrategy(S3RetryStrategy):
    ...

class S3FileSystem(FileSystem):

    def __init__(self, *, access_key=None, secret_key=None, session_token=None, anonymous: bool=False, region=None, request_timeout=None, connect_timeout=None, scheme=None, endpoint_override=None, background_writes: bool=True, default_metadata=None, role_arn=None, session_name=None, external_id=None, load_frequency: int=900, proxy_options=None, allow_delayed_open: bool=False, allow_bucket_creation: bool=False, allow_bucket_deletion: bool=False, check_directory_existence_before_creation: bool=False, retry_strategy: S3RetryStrategy=AwsStandardS3RetryStrategy(max_attempts=3), force_virtual_addressing: bool=False, tls_ca_file_path=None):
        ...

    @staticmethod
    def _reconstruct(kwargs) -> S3FileSystem:
        ...

    def __reduce__(self) -> tuple:
        ...

    @property
    def region(self) -> str:
        ...
