# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# Generated by stubgen-pyx from python/pyarrow/_substrait.pyx

import os
import re
import pyarrow
from typing import Any, Callable, IO, Iterable, Iterator, Literal, Mapping, NamedTuple, Self, Sequence
import pyarrow.compute
from pyarrow.lib import _Weakrefable
from _typeshed import Incomplete
from pyarrow.lib import *
from types import ModuleType

def run_query(plan, *, table_provider: object | None=None, use_threads: bool=True) -> pyarrow.RecordBatchReader:
    ...

def _parse_json_plan(plan: bytes) -> pyarrow.Buffer:
    ...

def serialize_schema(schema: pyarrow.Schema) -> SubstraitSchema:
    ...

def _serialize_namedstruct_schema(schema):
    ...

def deserialize_schema(buf: pyarrow.Buffer | bytes | SubstraitSchema) -> pyarrow.Schema:
    ...

def serialize_expressions(exprs: list[pyarrow.compute.Expression], names: list[str], schema: pyarrow.Schema, *, allow_arrow_extensions: bool=False) -> pyarrow.Buffer:
    ...

def deserialize_expressions(buf: pyarrow.Buffer | bytes) -> BoundExpressions:
    ...

def get_supported_functions() -> list:
    ...
py_substrait: ModuleType | None

class SubstraitSchema:

    def __init__(self, schema, expression):
        ...

    def to_pysubstrait(self):
        ...

class BoundExpressions(_Weakrefable):

    def __init__(self):
        ...

    @property
    def schema(self) -> pyarrow.Schema:
        ...

    @property
    def expressions(self) -> dict:
        ...

    @classmethod
    def from_substrait(cls, message) -> BoundExpressions:
        ...
