# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Generated by stubgen-pyx from python/pyarrow/_substrait.pyx
from _typeshed import Incomplete

from pyarrow.includes.libarrow import *
from pyarrow.includes.libarrow_substrait import *
from pyarrow.lib import *


class SubstraitSchema:
    def __init__(self, schema, expression): ...
    def to_pysubstrait(self): ...

class BoundExpressions(_Weakrefable):
    def __init__(self): ...
    @property
    def schema(self): ...
    @property
    def expressions(self): ...
    @classmethod
    def from_substrait(cls, message): ...

def run_query(plan, *, table_provider=None, use_threads=True): ...
def _parse_json_plan(plan): ...
def serialize_schema(schema): ...
def _serialize_namedstruct_schema(schema): ...
def deserialize_schema(buf): ...
def serialize_expressions(exprs, names, schema, *, allow_arrow_extensions=False): ...
def deserialize_expressions(buf): ...
def get_supported_functions(): ...

from types import ModuleType
py_substrait: ModuleType | None
