from pyarrow._acero import AggregateNodeOptions as AggregateNodeOptions, AsofJoinNodeOptions as AsofJoinNodeOptions, Declaration as Declaration, ExecNodeOptions as ExecNodeOptions, FilterNodeOptions as FilterNodeOptions, HashJoinNodeOptions as HashJoinNodeOptions, OrderByNodeOptions as OrderByNodeOptions, ProjectNodeOptions as ProjectNodeOptions, RecordBatchReaderSourceNodeOptions as RecordBatchReaderSourceNodeOptions, TableSourceNodeOptions as TableSourceNodeOptions
from pyarrow._dataset import ScanNodeOptions as ScanNodeOptions
from pyarrow.compute import Expression as Expression, field as field
from pyarrow.lib import RecordBatch as RecordBatch, Table as Table, array as array

class DatasetModuleStub:
    class Dataset: ...
    class InMemoryDataset: ...
ds = DatasetModuleStub

def _dataset_to_decl(dataset, use_threads: bool = True, implicit_ordering: bool = False): ...
def _perform_join(join_type, left_operand, left_keys, right_operand, right_keys, left_suffix=None, right_suffix=None, use_threads: bool = True, coalesce_keys: bool = False, output_type=..., filter_expression=None): ...
def _perform_join_asof(left_operand, left_on, left_by, right_operand, right_on, right_by, tolerance, use_threads: bool = True, output_type=...): ...
def _filter_table(table, expression): ...
def _sort_source(table_or_dataset, sort_keys, output_type=..., **kwargs): ...
def _group_by(table, aggregates, keys, use_threads: bool = True): ...
