from _typeshed import Incomplete
from pyarrow import _feather as _feather
from pyarrow._feather import FeatherError as FeatherError
from pyarrow.lib import Codec as Codec, Table as Table, concat_tables as concat_tables, schema as schema
from pyarrow.pandas_compat import _pandas_api as _pandas_api

class FeatherDataset:
    paths: Incomplete
    validate_schema: Incomplete
    def __init__(self, path_or_paths, validate_schema: bool = True) -> None: ...
    _tables: Incomplete
    schema: Incomplete
    def read_table(self, columns=None): ...
    def validate_schemas(self, piece, table) -> None: ...
    def read_pandas(self, columns=None, use_threads: bool = True): ...

def check_chunked_overflow(name, col) -> None: ...

_FEATHER_SUPPORTED_CODECS: Incomplete

def write_feather(df, dest, compression=None, compression_level=None, chunksize=None, version: int = 2) -> None: ...
def read_feather(source, columns=None, use_threads: bool = True, memory_map: bool = False, **kwargs): ...
def _read_table_internal(source, columns=None, memory_map: bool = False, use_threads: bool = True): ...
def read_table(source, columns=None, memory_map: bool = False, use_threads: bool = True): ...
