# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# Generated by stubgen-pyx from python/pyarrow/lib.pyx

import os
import re
import pyarrow
from typing import Callable, IO, Iterable, Iterator, Literal, NamedTuple, Self
import pyarrow.compute
from _typeshed import Incomplete
import sys
from collections import namedtuple
from collections.abc import Mapping, Sequence
from enum import IntEnum
from typing import Any
from typing_extensions import TypeAlias
MonthDayNano: Incomplete
Type_NA: Incomplete
Type_BOOL: Incomplete
Type_UINT8: Incomplete
Type_INT8: Incomplete
Type_UINT16: Incomplete
Type_INT16: Incomplete
Type_UINT32: Incomplete
Type_INT32: Incomplete
Type_UINT64: Incomplete
Type_INT64: Incomplete
Type_HALF_FLOAT: Incomplete
Type_FLOAT: Incomplete
Type_DOUBLE: Incomplete
Type_DECIMAL32: Incomplete
Type_DECIMAL64: Incomplete
Type_DECIMAL128: Incomplete
Type_DECIMAL256: Incomplete
Type_DATE32: Incomplete
Type_DATE64: Incomplete
Type_TIMESTAMP: Incomplete
Type_TIME32: Incomplete
Type_TIME64: Incomplete
Type_DURATION: Incomplete
Type_INTERVAL_MONTH_DAY_NANO: Incomplete
Type_BINARY: Incomplete
Type_STRING: Incomplete
Type_LARGE_BINARY: Incomplete
Type_LARGE_STRING: Incomplete
Type_FIXED_SIZE_BINARY: Incomplete
Type_BINARY_VIEW: Incomplete
Type_STRING_VIEW: Incomplete
Type_LIST: Incomplete
Type_LARGE_LIST: Incomplete
Type_LIST_VIEW: Incomplete
Type_LARGE_LIST_VIEW: Incomplete
Type_MAP: Incomplete
Type_FIXED_SIZE_LIST: Incomplete
Type_STRUCT: Incomplete
Type_SPARSE_UNION: Incomplete
Type_DENSE_UNION: Incomplete
Type_DICTIONARY: Incomplete
Type_RUN_END_ENCODED: Incomplete
Type_INTERVAL_MONTHS: Incomplete
Type_INTERVAL_DAY_TIME: Incomplete
UnionMode_SPARSE: Incomplete
UnionMode_DENSE: Incomplete
__pc: Incomplete
__pac: Incomplete
__cuda_loaded: Incomplete
ordered_dict = dict
ArrowIOError = IOError
have_signal_refcycle: bool
build_info: BuildInfo
cpp_build_info: CppBuildInfo
cpp_version: str
cpp_version_info: VersionInfo
_pandas_api: Incomplete
_python_extension_types_registry: list[Incomplete]
_registry_nanny: _ExtensionRegistryNanny
DEFAULT_BUFFER_SIZE: int

def cpu_count():
    ...

def set_cpu_count(count: int) -> None:
    ...

def is_opentelemetry_enabled() -> bool:
    ...

def is_threading_enabled() -> bool:
    ...

def _pc():
    ...

def _pac():
    ...

def _ensure_cuda_loaded() -> None:
    ...

def _gdb_test_session() -> None:
    ...

def encode_file_path(path):
    ...

def tobytes(o: str | bytes):
    ...

def frombytes(o, *, safe: bool=False):
    ...

def enable_signal_handlers(enable: bool) -> None:
    ...

def runtime_info() -> RuntimeInfo:
    ...

def _build_info() -> BuildInfo:
    ...

def set_timezone_db_path(path: str) -> None:
    ...

def default_memory_pool() -> MemoryPool:
    ...

def proxy_memory_pool(parent: MemoryPool) -> ProxyMemoryPool:
    ...

def logging_memory_pool(parent: MemoryPool) -> LoggingMemoryPool:
    ...

def system_memory_pool() -> MemoryPool:
    ...

def jemalloc_memory_pool() -> MemoryPool:
    ...

def mimalloc_memory_pool() -> MemoryPool:
    ...

def set_memory_pool(pool: MemoryPool) -> None:
    ...

def log_memory_allocations(enable: bool=True) -> None:
    ...

def total_allocated_bytes():
    ...

def jemalloc_set_decay_ms(decay_ms: int) -> None:
    ...

def supported_memory_backends() -> list:
    ...

def default_cpu_memory_manager() -> MemoryManager:
    ...

def _get_pandas_type_map():
    ...

def _is_primitive(type: int):
    ...

def _is_nested(type: int):
    ...

def _get_pandas_type(arrow_type, coerce_to_ns: bool=False):
    ...

def _get_pandas_tz_type(arrow_type, coerce_to_ns: bool=False):
    ...

def _to_pandas_dtype(arrow_type, options=None):
    ...

def register_extension_type(ext_type) -> None:
    ...

def unregister_extension_type(type_name: str) -> None:
    ...

def ensure_metadata(meta: object, allow_none: bool=False) -> KeyValueMetadata:
    ...

def unify_schemas(schemas: list[Schema], *, promote_options: str='default') -> Schema:
    ...

def field(name: str | bytes, type: DataType | str | None=None, nullable: bool | None=None, metadata: dict | None=None) -> Field:
    ...

def null() -> DataType:
    ...

def bool_() -> DataType:
    ...

def uint8() -> DataType:
    ...

def int8() -> DataType:
    ...

def uint16() -> DataType:
    ...

def int16() -> DataType:
    ...

def uint32() -> DataType:
    ...

def int32() -> DataType:
    ...

def uint64() -> DataType:
    ...

def int64() -> DataType:
    ...

def tzinfo_to_string(tz) -> str:
    ...

def string_to_tzinfo(name, *, prefer_zoneinfo: bool=True):
    ...

def timestamp(unit: str, tz: str | None=None) -> TimestampType:
    ...

def time32(unit: str) -> Time32Type:
    ...

def time64(unit: str) -> Time64Type:
    ...

def duration(unit: str) -> DurationType:
    ...

def month_day_nano_interval() -> DataType:
    ...

def date32() -> DataType:
    ...

def date64() -> DataType:
    ...

def float16() -> DataType:
    ...

def float32() -> DataType:
    ...

def float64() -> DataType:
    ...

def decimal32(precision: int, scale: int=0) -> DataType:
    ...

def decimal64(precision: int, scale: int=0) -> DataType:
    ...

def decimal128(precision: int, scale: int=0) -> DataType:
    ...

def decimal256(precision: int, scale: int=0) -> DataType:
    ...

def string() -> DataType:
    ...

def utf8():
    ...

def binary(length: int=-1) -> DataType:
    ...

def large_binary() -> DataType:
    ...

def large_string() -> DataType:
    ...

def large_utf8():
    ...

def binary_view() -> DataType:
    ...

def string_view() -> DataType:
    ...

def list_(value_type: DataType | Field, list_size: int=-1) -> DataType:
    ...

def large_list(value_type: DataType | Field) -> LargeListType:
    ...

def list_view(value_type: DataType | Field) -> ListViewType:
    ...

def large_list_view(value_type: DataType | Field) -> LargeListViewType:
    ...

def map_(key_type: DataType | Field, item_type: DataType | Field, keys_sorted: bool=False) -> MapType:
    ...

def dictionary(index_type: DataType, value_type: DataType, ordered: bool=False) -> DictionaryType:
    ...

def struct(fields) -> DataType:
    ...

def sparse_union(child_fields, type_codes: list[int] | None=None) -> DataType:
    ...

def dense_union(child_fields, type_codes: list[int] | None=None) -> DataType:
    ...

def union(child_fields, mode: str, type_codes: list[int] | None=None) -> UnionType:
    ...

def run_end_encoded(run_end_type: DataType, value_type: DataType) -> DataType:
    ...

def json_(storage_type: DataType=utf8()) -> JsonType:
    ...

def uuid() -> UuidType:
    ...

def fixed_shape_tensor(value_type: DataType, shape: tuple | list[int], dim_names: tuple | list[str] | None=None, permutation=None) -> FixedShapeTensorType:
    ...

def bool8() -> Bool8Type:
    ...

def opaque(storage_type: DataType, type_name: str, vendor_name: str) -> OpaqueType:
    ...

def type_for_alias(name: str) -> DataType:
    ...

def ensure_type(ty: object, allow_none: bool=False) -> DataType:
    ...

def schema(fields, metadata: dict | None=None) -> Schema:
    ...

def from_numpy_dtype(dtype: object) -> DataType:
    ...

def is_boolean_value(obj: object):
    ...

def is_integer_value(obj: object):
    ...

def is_float_value(obj: object):
    ...

def _datetime_from_int(value: int, unit: int, tzinfo=None):
    ...

def scalar(value: Any, type: DataType | None=None, *, from_pandas: bool | None=None, memory_pool: MemoryPool | None=None) -> Scalar:
    ...

def _ndarray_to_arrow_type(values: object, type: DataType) -> DataType:
    ...

def _handle_arrow_array_protocol(obj, type, mask, size):
    ...

def array(obj: object, type: DataType | None=None, mask=None, size=None, from_pandas: bool | None=None, safe: bool=True, memory_pool: MemoryPool | None=None) -> Array | ChunkedArray:
    ...

def asarray(values, type: str | DataType | None=None) -> Array | ChunkedArray:
    ...

def nulls(size: int, type: DataType | None=None, memory_pool: MemoryPool | None=None) -> Array:
    ...

def repeat(value, size: int, memory_pool: MemoryPool | None=None) -> Array:
    ...

def infer_type(values, mask=None, from_pandas: bool=False) -> DataType:
    ...

def arange(start: int, stop: int, step: int=1, *, memory_pool: MemoryPool | None=None) -> Array:
    ...

def _normalize_slice(arrow_obj: object, key: slice):
    ...

def _restore_array(data) -> Array:
    ...

def _compute_binary_op(func_name, left, right):
    ...

def concat_arrays(arrays: Iterable[Array], memory_pool: MemoryPool | None=None) -> Array:
    ...

def _empty_array(type: DataType) -> DictionaryArray:
    ...

def chunked_array(arrays, type=None) -> ChunkedArray:
    ...

def _reconstruct_record_batch(columns, schema) -> RecordBatch:
    ...

def table_to_blocks(options, table: Table, categories, extension_columns):
    ...

def _reconstruct_table(arrays, schema) -> Table:
    ...

def record_batch(data, names: list | None=None, schema: Schema | None=None, metadata: dict | Mapping[Any, Any] | None=None) -> RecordBatch:
    ...

def table(data, names: list | None=None, schema: Schema | None=None, metadata: dict | Mapping[Any, Any] | None=None, nthreads: int | None=None) -> Table:
    ...

def concat_tables(tables, memory_pool: MemoryPool | None=None, promote_options: str='none', **kwargs) -> Table:
    ...

def concat_batches(recordbatches, memory_pool: MemoryPool | None=None) -> RecordBatch:
    ...

def _from_pydict(cls, mapping: dict | Mapping[Any, Any], schema: Schema | None, metadata: dict | Mapping[Any, Any] | None) -> Self:
    ...

def _from_pylist(cls, mapping, schema: Schema | None, metadata: dict | Mapping[Any, Any] | None) -> Self:
    ...

def io_thread_count():
    ...

def set_io_thread_count(count: int) -> None:
    ...

def memory_map(path: str, mode: str='r') -> MemoryMappedFile:
    ...

def create_memory_map(path: str, size: int) -> MemoryMappedFile:
    ...

def allocate_buffer(size: int, memory_pool: MemoryPool | None=None, resizable: bool=False) -> ResizableBuffer | Buffer:
    ...

def transcoding_input_stream(stream: NativeFile, src_encoding: str, dest_encoding: str):
    ...

def py_buffer(obj: object) -> Buffer:
    ...

def foreign_buffer(address: int, size: int, base=None) -> Buffer:
    ...

def as_buffer(o: object):
    ...

def _detect_compression(path) -> str:
    ...

def compress(buf: object, codec: str='lz4', asbytes: bool=False, memory_pool: MemoryPool | None=None) -> Buffer | bytes:
    ...

def decompress(buf: object, decompressed_size: int | None=None, codec: str='lz4', asbytes: bool=False, memory_pool: MemoryPool | None=None) -> Buffer | bytes:
    ...

def input_stream(source, compression: str | None='detect', buffer_size: int | None=None) -> NativeFile:
    ...

def output_stream(source, compression: str | None='detect', buffer_size: int | None=None) -> NativeFile:
    ...

def get_tensor_size(tensor: Tensor) -> int:
    ...

def get_record_batch_size(batch: RecordBatch) -> int:
    ...

def write_tensor(tensor: Tensor, dest: NativeFile) -> int:
    ...

def read_tensor(source: NativeFile) -> Tensor:
    ...

def read_message(source) -> Message:
    ...

def read_schema(obj, dictionary_memo: DictionaryMemo | None=None) -> Schema:
    ...

def read_record_batch(obj, schema: Schema, dictionary_memo: DictionaryMemo | None=None) -> RecordBatch:
    ...

def benchmark_PandasObjectIsNull(obj: list[Any]) -> None:
    ...
_NULL: NullScalar
NA: NullScalar

class VersionInfo(NamedTuple):
    major: Incomplete
    minor: Incomplete
    patch: Incomplete

class RuntimeInfo(NamedTuple):
    simd_level: Incomplete
    detected_simd_level: Incomplete

class BuildInfo(NamedTuple):
    build_type: Incomplete
    cpp_build_info: Incomplete

class CppBuildInfo(NamedTuple):
    version: Incomplete
    version_info: Incomplete
    so_version: Incomplete
    full_so_version: Incomplete
    compiler_id: Incomplete
    compiler_version: Incomplete
    compiler_flags: Incomplete
    git_id: Incomplete
    git_description: Incomplete
    package_kind: Incomplete
    build_type: Incomplete

class _WriteStats(NamedTuple):
    num_messages: Incomplete
    num_record_batches: Incomplete
    num_dictionary_batches: Incomplete
    num_dictionary_deltas: Incomplete
    num_replaced_dictionaries: Incomplete

class _ReadStats(NamedTuple):
    num_messages: Incomplete
    num_record_batches: Incomplete
    num_dictionary_batches: Incomplete
    num_dictionary_deltas: Incomplete
    num_replaced_dictionaries: Incomplete

class _RecordBatchWithMetadata(NamedTuple):
    batch: Incomplete
    custom_metadata: Incomplete

class DeviceAllocationType(IntEnum):
    CPU = ...
    CUDA = ...
    CUDA_HOST = ...
    OPENCL = ...
    VULKAN = ...
    METAL = ...
    VPI = ...
    ROCM = ...
    ROCM_HOST = ...
    EXT_DEV = ...
    CUDA_MANAGED = ...
    ONEAPI = ...
    WEBGPU = ...
    HEXAGON = ...

class MetadataVersion(IntEnum):
    V1 = ...
    V2 = ...
    V3 = ...
    V4 = ...
    V5 = ...

class Alignment(IntEnum):
    Any = ...
    DataTypeSpecific = ...
    At64Byte = ...

class ArrowException(Exception):
    ...

class ArrowInvalid(ValueError, ArrowException):
    ...

class ArrowMemoryError(MemoryError, ArrowException):
    ...

class ArrowKeyError(KeyError, ArrowException):

    def __str__(self):
        ...

class ArrowTypeError(TypeError, ArrowException):
    ...

class ArrowNotImplementedError(NotImplementedError, ArrowException):
    ...

class ArrowCapacityError(ArrowException):
    ...

class ArrowIndexError(IndexError, ArrowException):
    ...

class ArrowSerializationError(ArrowException):
    ...

class ArrowCancelled(ArrowException):

    def __init__(self, message, signum=None):
        ...

class StopToken:
    ...

class SignalStopHandler:

    def __init__(self):
        ...

    def _init_signals(self) -> None:
        ...

    def __enter__(self) -> Self:
        ...

    def __exit__(self, exc_type, exc_value, exc_tb) -> None:
        ...

    @property
    def stop_token(self):
        ...

class _PandasAPIShim(object):
    _loose_version: object
    _version: object
    _pd: object
    _types_api: object
    _compat_module: object
    _data_frame: object
    _index: object
    _series: object
    _categorical_type: object
    _datetimetz_type: object
    _extension_array: object
    _extension_dtype: object
    _array_like_types: object
    _lock: object
    _is_ge_v23: bool
    _is_ge_v3: bool
    _is_ge_v3_strict: bool

    def __init__(self):
        ...

    def series(self, *args, **kwargs):
        ...

    def data_frame(self, *args, **kwargs):
        ...

    @property
    def have_pandas(self):
        ...

    @property
    def compat(self):
        ...

    @property
    def pd(self):
        ...

    def infer_dtype(self, obj):
        ...

    def pandas_dtype(self, dtype):
        ...

    @property
    def loose_version(self):
        ...

    @property
    def version(self):
        ...

    def is_ge_v23(self):
        ...

    def is_ge_v3(self):
        ...

    def is_ge_v3_strict(self):
        ...

    def uses_string_dtype(self):
        ...

    @property
    def categorical_type(self):
        ...

    @property
    def datetimetz_type(self):
        ...

    @property
    def extension_dtype(self):
        ...

    def is_array_like(self, obj):
        ...

    def is_categorical(self, obj):
        ...

    def is_datetimetz(self, obj):
        ...

    def is_extension_array_dtype(self, obj):
        ...

    def is_sparse(self, obj):
        ...

    def is_data_frame(self, obj):
        ...

    def is_series(self, obj):
        ...

    def is_index(self, obj):
        ...

    def get_values(self, obj):
        ...

class _Weakrefable:
    ...

class MemoryPool(_Weakrefable):

    def __init__(self):
        ...

    def release_unused(self) -> None:
        ...

    def bytes_allocated(self):
        ...

    def total_bytes_allocated(self):
        ...

    def max_memory(self):
        ...

    def num_allocations(self):
        ...

    def print_stats(self) -> None:
        ...

    @property
    def backend_name(self) -> str:
        ...

    def __repr__(self) -> str:
        ...

class LoggingMemoryPool(MemoryPool):

    def __init__(self):
        ...

class ProxyMemoryPool(MemoryPool):

    def __init__(self):
        ...

class Device(_Weakrefable):

    def __init__(self):
        ...

    def __eq__(self, other):
        ...

    def __repr__(self) -> str:
        ...

    @property
    def type_name(self) -> str:
        ...

    @property
    def device_id(self):
        ...

    @property
    def is_cpu(self):
        ...

    @property
    def device_type(self):
        ...

class MemoryManager(_Weakrefable):

    def __init__(self):
        ...

    def __repr__(self) -> str:
        ...

    @property
    def device(self) -> Device:
        ...

    @property
    def is_cpu(self):
        ...

class DataType(_Weakrefable):

    def __init__(self):
        ...

    def field(self, i: int) -> Field:
        ...

    @property
    def id(self):
        ...

    @property
    def bit_width(self):
        ...

    @property
    def byte_width(self):
        ...

    @property
    def num_fields(self):
        ...

    @property
    def num_buffers(self):
        ...

    @property
    def has_variadic_buffers(self):
        ...

    def __str__(self) -> str:
        ...

    def __hash__(self):
        ...

    def __reduce__(self) -> tuple:
        ...

    def __repr__(self) -> str:
        ...

    def __eq__(self, other):
        ...

    def equals(self, other, *, check_metadata: bool=False) -> bool:
        ...

    def to_pandas_dtype(self):
        ...

    def _export_to_c(self, out_ptr) -> None:
        ...

    @staticmethod
    def _import_from_c(in_ptr) -> DataType:
        ...

    def __arrow_c_schema__(self):
        ...

    @staticmethod
    def _import_from_c_capsule(schema) -> DataType:
        ...

class DictionaryMemo(_Weakrefable):

    def __init__(self):
        ...

class DictionaryType(DataType):

    def __reduce__(self) -> tuple:
        ...

    @property
    def ordered(self):
        ...

    @property
    def index_type(self) -> DataType:
        ...

    @property
    def value_type(self) -> DataType:
        ...

class ListType(DataType):

    def __reduce__(self) -> tuple:
        ...

    @property
    def value_field(self) -> Field:
        ...

    @property
    def value_type(self) -> DataType:
        ...

class LargeListType(DataType):

    def __reduce__(self) -> tuple:
        ...

    @property
    def value_field(self) -> Field:
        ...

    @property
    def value_type(self) -> DataType:
        ...

class ListViewType(DataType):

    def __reduce__(self) -> tuple:
        ...

    @property
    def value_field(self) -> Field:
        ...

    @property
    def value_type(self) -> DataType:
        ...

class LargeListViewType(DataType):

    def __reduce__(self) -> tuple:
        ...

    @property
    def value_field(self) -> Field:
        ...

    @property
    def value_type(self) -> DataType:
        ...

class MapType(DataType):

    def __reduce__(self) -> tuple:
        ...

    @property
    def key_field(self) -> Field:
        ...

    @property
    def key_type(self) -> DataType:
        ...

    @property
    def item_field(self) -> Field:
        ...

    @property
    def item_type(self) -> DataType:
        ...

    @property
    def keys_sorted(self):
        ...

class FixedSizeListType(DataType):

    def __reduce__(self) -> tuple:
        ...

    @property
    def value_field(self) -> Field:
        ...

    @property
    def value_type(self) -> DataType:
        ...

    @property
    def list_size(self):
        ...

class StructType(DataType):

    def get_field_index(self, name: str) -> int:
        ...

    def field(self, i: int | str) -> Field:
        ...

    def get_all_field_indices(self, name: str) -> list[int]:
        ...

    def __len__(self):
        ...

    def __iter__(self) -> Iterator[Any]:
        ...

    def __getitem__(self, i):
        ...

    def __reduce__(self) -> tuple:
        ...

    @property
    def names(self) -> list:
        ...

    @property
    def fields(self) -> list:
        ...

class UnionType(DataType):

    @property
    def mode(self) -> str:
        ...

    @property
    def type_codes(self):
        ...

    def __len__(self):
        ...

    def __iter__(self) -> Iterator[Any]:
        ...

    def field(self, i: int) -> Field:
        ...

    def __getitem__(self, i):
        ...

    def __reduce__(self) -> tuple:
        ...

class SparseUnionType(UnionType):
    ...

class DenseUnionType(UnionType):
    ...

class TimestampType(DataType):

    @property
    def unit(self):
        ...

    @property
    def tz(self) -> str | None:
        ...

    def __reduce__(self) -> tuple:
        ...

class Time32Type(DataType):

    @property
    def unit(self):
        ...

class Time64Type(DataType):

    @property
    def unit(self):
        ...

class DurationType(DataType):

    @property
    def unit(self):
        ...

class FixedSizeBinaryType(DataType):

    def __reduce__(self) -> tuple:
        ...

class Decimal32Type(FixedSizeBinaryType):

    def __reduce__(self) -> tuple:
        ...

    @property
    def precision(self):
        ...

    @property
    def scale(self):
        ...

class Decimal64Type(FixedSizeBinaryType):

    def __reduce__(self) -> tuple:
        ...

    @property
    def precision(self):
        ...

    @property
    def scale(self):
        ...

class Decimal128Type(FixedSizeBinaryType):

    def __reduce__(self) -> tuple:
        ...

    @property
    def precision(self):
        ...

    @property
    def scale(self):
        ...

class Decimal256Type(FixedSizeBinaryType):

    def __reduce__(self) -> tuple:
        ...

    @property
    def precision(self):
        ...

    @property
    def scale(self):
        ...

class RunEndEncodedType(DataType):

    def __reduce__(self) -> tuple:
        ...

    @property
    def run_end_type(self) -> DataType:
        ...

    @property
    def value_type(self) -> DataType:
        ...

class BaseExtensionType(DataType):

    def __arrow_ext_class__(self):
        ...

    def __arrow_ext_scalar_class__(self):
        ...

    @property
    def extension_name(self) -> str:
        ...

    @property
    def storage_type(self) -> DataType:
        ...

    @property
    def byte_width(self):
        ...

    @property
    def bit_width(self):
        ...

    def wrap_array(self, storage: Array | ChunkedArray) -> Array | ChunkedArray:
        ...

class ExtensionType(BaseExtensionType):

    def __init__(self, storage_type: DataType, extension_name):
        ...

    def __eq__(self, other):
        ...

    def __repr__(self) -> str:
        ...

    def __arrow_ext_serialize__(self):
        ...

    @classmethod
    def __arrow_ext_deserialize__(cls, storage_type, serialized):
        ...

    def __reduce__(self) -> tuple:
        ...

    def __arrow_ext_class__(self):
        ...

    def __arrow_ext_scalar_class__(self):
        ...

class JsonType(BaseExtensionType):

    def __arrow_ext_class__(self):
        ...

    def __reduce__(self) -> tuple:
        ...

    def __arrow_ext_scalar_class__(self):
        ...

class UuidType(BaseExtensionType):

    def __arrow_ext_class__(self):
        ...

    def __reduce__(self) -> tuple:
        ...

    def __arrow_ext_scalar_class__(self):
        ...

class FixedShapeTensorType(BaseExtensionType):

    @property
    def value_type(self) -> DataType:
        ...

    @property
    def shape(self):
        ...

    @property
    def dim_names(self) -> list | None:
        ...

    @property
    def permutation(self):
        ...

    def __arrow_ext_class__(self):
        ...

    def __reduce__(self) -> tuple:
        ...

    def __arrow_ext_scalar_class__(self):
        ...

class Bool8Type(BaseExtensionType):

    def __arrow_ext_class__(self):
        ...

    def __reduce__(self) -> tuple:
        ...

    def __arrow_ext_scalar_class__(self):
        ...

class OpaqueType(BaseExtensionType):

    @property
    def type_name(self) -> str:
        ...

    @property
    def vendor_name(self) -> str:
        ...

    def __arrow_ext_class__(self):
        ...

    def __reduce__(self) -> tuple:
        ...

    def __arrow_ext_scalar_class__(self):
        ...

class UnknownExtensionType(ExtensionType):

    def __init__(self, storage_type: DataType, serialized):
        ...

    def __arrow_ext_serialize__(self):
        ...

    @classmethod
    def __arrow_ext_deserialize__(cls, storage_type, serialized) -> UnknownExtensionType:
        ...

class _Metadata(_Weakrefable):
    ...

class KeyValueMetadata(_Metadata, Mapping):

    def __init__(self, __arg0__=None, **kwargs):
        ...

    def equals(self, other: KeyValueMetadata) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __str__(self) -> str:
        ...

    def __eq__(self, other):
        ...

    def __len__(self):
        ...

    def __contains__(self, key):
        ...

    def __getitem__(self, key):
        ...

    def __iter__(self):
        ...

    def __reduce__(self) -> tuple:
        ...

    def key(self, i: int):
        ...

    def value(self, i: int):
        ...

    def keys(self) -> Iterator[Any]:
        ...

    def values(self) -> Iterator[Any]:
        ...

    def items(self) -> Iterator[tuple]:
        ...

    def get_all(self, key: str) -> list:
        ...

    def to_dict(self):
        ...

class Field(_Weakrefable):
    type: DataType

    def __init__(self):
        ...

    def equals(self, other: Field, check_metadata: bool=False) -> bool:
        ...

    def __eq__(self, other):
        ...

    def __reduce__(self) -> tuple:
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self):
        ...

    def __hash__(self):
        ...

    @property
    def nullable(self):
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def metadata(self) -> dict | None:
        ...

    def with_metadata(self, metadata: dict) -> Field:
        ...

    def remove_metadata(self) -> Field:
        ...

    def with_type(self, new_type: DataType) -> Field:
        ...

    def with_name(self, name: str) -> Field:
        ...

    def with_nullable(self, nullable: bool) -> Field:
        ...

    def flatten(self) -> list:
        ...

    def _export_to_c(self, out_ptr) -> None:
        ...

    @staticmethod
    def _import_from_c(in_ptr) -> Field:
        ...

    def __arrow_c_schema__(self):
        ...

    @staticmethod
    def _import_from_c_capsule(schema) -> Field:
        ...

class Schema(_Weakrefable):

    def __init__(self):
        ...

    def __len__(self):
        ...

    def __getitem__(self, key):
        ...

    def __iter__(self) -> Iterator[Any]:
        ...

    def __reduce__(self) -> tuple:
        ...

    def __hash__(self):
        ...

    def __sizeof__(self):
        ...

    @property
    def pandas_metadata(self):
        ...

    @property
    def names(self) -> list:
        ...

    @property
    def types(self) -> list:
        ...

    @property
    def metadata(self):
        ...

    def __eq__(self, other):
        ...

    def empty_table(self) -> Table:
        ...

    def equals(self, other: Schema, check_metadata: bool=False) -> bool:
        ...

    @classmethod
    def from_pandas(cls, df, preserve_index: bool | None=None) -> Schema:
        ...

    def field(self, i: int | str) -> Field:
        ...

    def _field(self, i: int) -> Field:
        ...

    def field_by_name(self, name: str) -> None | Field:
        ...

    def get_field_index(self, name: str) -> int:
        ...

    def get_all_field_indices(self, name: str) -> list[int]:
        ...

    def append(self, field: Field):
        ...

    def insert(self, i: int, field: Field) -> Schema:
        ...

    def remove(self, i: int) -> Schema:
        ...

    def set(self, i: int, field: Field) -> Schema:
        ...

    def add_metadata(self, metadata: dict):
        ...

    def with_metadata(self, metadata: dict) -> Schema:
        ...

    def serialize(self, memory_pool: MemoryPool | None=None) -> Buffer:
        ...

    def remove_metadata(self) -> Schema:
        ...

    def to_string(self, truncate_metadata: bool=True, show_field_metadata: bool=True, show_schema_metadata: bool=True, element_size_limit: int=100) -> str:
        ...

    def _export_to_c(self, out_ptr) -> None:
        ...

    @staticmethod
    def _import_from_c(in_ptr) -> Schema:
        ...

    def __str__(self):
        ...

    def __repr__(self):
        ...

    def __arrow_c_schema__(self):
        ...

    @staticmethod
    def _import_from_c_capsule(schema) -> Schema:
        ...

class _ExtensionRegistryNanny(_Weakrefable):

    def __init__(self):
        ...

    def release_registry(self) -> None:
        ...

class Scalar(_Weakrefable):

    def __init__(self):
        ...

    @property
    def type(self) -> DataType:
        ...

    @property
    def is_valid(self):
        ...

    def cast(self, target_type: object | None=None, safe: bool | None=None, options: pyarrow.compute.CastOptions | None=None, memory_pool: MemoryPool | None=None):
        ...

    def validate(self, *, full: bool=False) -> None:
        ...

    def __repr__(self) -> str:
        ...

    def __str__(self) -> str:
        ...

    def equals(self, other: Scalar) -> bool:
        ...

    def __eq__(self, other):
        ...

    def __hash__(self):
        ...

    def __reduce__(self) -> tuple:
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __abs__(self):
        ...

    def __add__(self, other: object):
        ...

    def __radd__(self, other: object):
        ...

    def __truediv__(self, other: object):
        ...

    def __rtruediv__(self, other: object):
        ...

    def __mul__(self, other: object):
        ...

    def __rmul__(self, other: object):
        ...

    def __neg__(self):
        ...

    def __pow__(self, other: object, mod: None=None):
        ...

    def __rpow__(self, other: object, mod: None=None):
        ...

    def __sub__(self, other: object):
        ...

    def __rsub__(self, other: object):
        ...

    def __and__(self, other: object):
        ...

    def __rand__(self, other: object):
        ...

    def __or__(self, other: object):
        ...

    def __ror__(self, other: object):
        ...

    def __xor__(self, other: object):
        ...

    def __rxor__(self, other: object):
        ...

    def __lshift__(self, other: object):
        ...

    def __rlshift__(self, other: object):
        ...

    def __rshift__(self, other: object):
        ...

    def __rrshift__(self, other: object):
        ...

class NullScalar(Scalar):

    def __init__(self):
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None) -> None:
        ...

class BooleanScalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __bool__(self):
        ...

class UInt8Scalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __index__(self):
        ...

class Int8Scalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __index__(self):
        ...

class UInt16Scalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __index__(self):
        ...

class Int16Scalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __index__(self):
        ...

class UInt32Scalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __index__(self):
        ...

class Int32Scalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __index__(self):
        ...

class UInt64Scalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __index__(self):
        ...

class Int64Scalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __index__(self):
        ...

class HalfFloatScalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __float__(self):
        ...

    def __int__(self) -> int:
        ...

class FloatScalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __float__(self):
        ...

    def __int__(self) -> int:
        ...

class DoubleScalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __float__(self):
        ...

    def __int__(self) -> int:
        ...

class Decimal32Scalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

class Decimal64Scalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

class Decimal128Scalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

class Decimal256Scalar(Scalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

class Date32Scalar(Scalar):

    @property
    def value(self):
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

class Date64Scalar(Scalar):

    @property
    def value(self):
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

class Time32Scalar(Scalar):

    @property
    def value(self):
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

class Time64Scalar(Scalar):

    @property
    def value(self):
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

class TimestampScalar(Scalar):

    @property
    def value(self):
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __repr__(self) -> str:
        ...

class DurationScalar(Scalar):

    @property
    def value(self):
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

class MonthDayNanoIntervalScalar(Scalar):

    @property
    def value(self):
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

class BinaryScalar(Scalar):

    def as_buffer(self) -> Buffer | None:
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    def __bytes__(self):
        ...

class LargeBinaryScalar(BinaryScalar):
    ...

class FixedSizeBinaryScalar(BinaryScalar):
    ...

class StringScalar(BinaryScalar):

    def as_py(self, *, maps_as_pydicts: str | None=None) -> None | str:
        ...

class LargeStringScalar(StringScalar):
    ...

class BinaryViewScalar(BinaryScalar):
    ...

class StringViewScalar(StringScalar):
    ...

class ListScalar(Scalar, Sequence):

    @property
    def values(self) -> Array | None:
        ...

    def __len__(self) -> int:
        ...

    def __getitem__(self, i):
        ...

    def __iter__(self):
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

class FixedSizeListScalar(ListScalar):
    ...

class LargeListScalar(ListScalar):
    ...

class ListViewScalar(ListScalar):
    ...

class LargeListViewScalar(ListScalar):
    ...

class StructScalar(Scalar, Mapping):

    def __len__(self):
        ...

    def __iter__(self) -> Iterator[str]:
        ...

    def items(self):
        ...

    def __contains__(self, key) -> bool:
        ...

    def __getitem__(self, key) -> Scalar:
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None) -> dict | None:
        ...

    def _as_py_tuple(self) -> list | None:
        ...

    def __repr__(self) -> str:
        ...

    def __str__(self) -> str:
        ...

class MapScalar(ListScalar, Mapping):

    def __getitem__(self, i):
        ...

    def __iter__(self) -> Iterator[tuple]:
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None) -> None | list | dict:
        ...

    def keys(self) -> list:
        ...

class DictionaryScalar(Scalar):

    @staticmethod
    def _reconstruct(type, is_valid, index, dictionary) -> Scalar:
        ...

    def __reduce__(self) -> tuple:
        ...

    @property
    def index(self) -> Scalar:
        ...

    @property
    def value(self) -> Scalar:
        ...

    @property
    def dictionary(self) -> Array:
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

class RunEndEncodedScalar(Scalar):

    @property
    def value(self) -> Scalar:
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

class UnionScalar(Scalar):

    @property
    def value(self) -> Scalar | None:
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    @property
    def type_code(self):
        ...

class ExtensionScalar(Scalar):

    @property
    def value(self) -> Scalar | None:
        ...

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

    @staticmethod
    def from_storage(typ: BaseExtensionType, value: object) -> Scalar:
        ...

class JsonScalar(ExtensionScalar):
    ...

class UuidScalar(ExtensionScalar):

    def as_py(self, *, maps_as_pydicts: str | None=None):
        ...

class FixedShapeTensorScalar(ExtensionScalar):

    def to_numpy(self):
        ...

    def to_tensor(self) -> Tensor:
        ...

    def __dlpack__(self, *, stream=None, max_version=None, dl_device=None, copy=None):
        ...

    def __dlpack_device__(self) -> tuple:
        ...

class OpaqueScalar(ExtensionScalar):
    ...

class Bool8Scalar(ExtensionScalar):

    def as_py(self, *, maps_as_pydicts: str | None=None) -> None | bool:
        ...

class ArrayStatistics(_Weakrefable):

    def __init__(self):
        ...

    def __repr__(self) -> str:
        ...

    @property
    def null_count(self):
        ...

    @property
    def is_null_count_exact(self):
        ...

    @property
    def distinct_count(self):
        ...

    @property
    def is_distinct_count_exact(self):
        ...

    @property
    def min(self):
        ...

    @property
    def is_min_exact(self):
        ...

    @property
    def max(self):
        ...

    @property
    def is_max_exact(self):
        ...

class _PandasConvertible(_Weakrefable):

    def to_pandas(self, memory_pool: MemoryPool | None=None, categories: list | None=None, strings_to_categorical: bool=False, zero_copy_only: bool=False, integer_object_nulls: bool=False, date_as_object: bool=True, timestamp_as_object: bool=False, use_threads: bool=True, deduplicate_objects: bool=True, ignore_metadata: bool=False, safe: bool=True, split_blocks: bool=False, self_destruct: bool=False, maps_as_pydicts: str | None=None, types_mapper: Callable[..., Any] | None=None, coerce_temporal_nanoseconds: bool=False):
        ...

class Array(_PandasConvertible):
    type: DataType
    _name: object

    def __init__(self):
        ...

    def _debug_print(self) -> None:
        ...

    def diff(self, other: Array) -> str:
        ...

    def cast(self, target_type: object | None=None, safe: bool | None=None, options: pyarrow.compute.CastOptions | None=None, memory_pool: MemoryPool | None=None) -> Array:
        ...

    def view(self, target_type: object) -> Array:
        ...

    def sum(self, **kwargs) -> Scalar:
        ...

    def unique(self) -> Array:
        ...

    def dictionary_encode(self, null_encoding: str='mask') -> DictionaryArray:
        ...

    def value_counts(self) -> StructArray:
        ...

    @staticmethod
    def from_pandas(obj, mask=None, type: DataType | None=None, safe: bool=True, memory_pool: MemoryPool | None=None) -> Array | ChunkedArray:
        ...

    def __reduce__(self) -> tuple:
        ...

    @staticmethod
    def from_buffers(type: DataType, length: int, buffers, null_count: int=-1, offset: int=0, children: list[Array] | None=None) -> Array:
        ...

    @property
    def null_count(self):
        ...

    @property
    def nbytes(self):
        ...

    def get_total_buffer_size(self) -> int:
        ...

    def __sizeof__(self):
        ...

    def __iter__(self) -> Iterator[Any]:
        ...

    def __repr__(self) -> str:
        ...

    def to_string(self, *, indent: int=2, top_level_indent: int=0, window: int=10, container_window: int=2, skip_new_lines: bool=False, element_size_limit: int=100) -> str:
        ...

    def __str__(self):
        ...

    def __eq__(self, other):
        ...

    def equals(self: Array, other: Array) -> bool:
        ...

    def __len__(self):
        ...

    def is_null(self, *, nan_is_null: bool=False):
        ...

    def is_nan(self):
        ...

    def is_valid(self):
        ...

    def fill_null(self, fill_value: Any) -> Array:
        ...

    def __getitem__(self, key) -> Scalar | Array:
        ...

    def slice(self, offset: int | Scalar=0, length: int | Scalar | None=None) -> Array:
        ...

    def take(self, indices: object) -> Array:
        ...

    def drop_null(self):
        ...

    def filter(self, mask: object, *, null_selection_behavior: str='drop') -> Array:
        ...

    def index(self, value: Scalar | object, start: int | None=None, end: int | None=None, *, memory_pool: MemoryPool | None=None) -> Int64Scalar:
        ...

    def sort(self, order: str='ascending', null_placement: str='at_end', **kwargs) -> Array:
        ...

    def _to_pandas(self, options, types_mapper=None, **kwargs):
        ...

    def __array__(self, dtype=None, copy=None):
        ...

    def to_numpy(self, zero_copy_only: bool=True, writable: bool=False):
        ...

    def to_tensor(self, *, allow_nulls: bool=False) -> Tensor:
        ...

    def to_pylist(self, *, maps_as_pydicts: str | None=None) -> list:
        ...

    def tolist(self):
        ...

    def validate(self, *, full: bool=False) -> None:
        ...

    @property
    def offset(self):
        ...

    def buffers(self) -> list:
        ...

    def copy_to(self, destination: MemoryManager | Device) -> Array:
        ...

    def _export_to_c(self, out_ptr, out_schema_ptr: int=0) -> None:
        ...

    @staticmethod
    def _import_from_c(in_ptr, type) -> Array:
        ...

    def __arrow_c_array__(self, requested_schema=None) -> tuple:
        ...

    @staticmethod
    def _import_from_c_capsule(schema_capsule, array_capsule) -> Array:
        ...

    def _export_to_c_device(self, out_ptr, out_schema_ptr: int=0) -> None:
        ...

    @staticmethod
    def _import_from_c_device(in_ptr, type) -> Array:
        ...

    def __arrow_c_device_array__(self, requested_schema=None, **kwargs) -> tuple:
        ...

    @staticmethod
    def _import_from_c_device_capsule(schema_capsule, array_capsule) -> Array:
        ...

    @staticmethod
    def from_dlpack(x: object, /, *, device=None, copy: bool | None=None) -> Array:
        ...

    def __dlpack__(self, *, stream: int | None=None, max_version=None, dl_device=None, copy: bool | None=None):
        ...

    def __dlpack_device__(self) -> tuple:
        ...

    @property
    def device_type(self) -> DeviceAllocationType:
        ...

    @property
    def is_cpu(self) -> bool:
        ...

    @property
    def statistics(self) -> None | ArrayStatistics:
        ...

    def __abs__(self):
        ...

    def __add__(self, other: object):
        ...

    def __radd__(self, other: object):
        ...

    def __truediv__(self, other: object):
        ...

    def __rtruediv__(self, other: object):
        ...

    def __mul__(self, other: object):
        ...

    def __rmul__(self, other: object):
        ...

    def __neg__(self):
        ...

    def __pow__(self, other: object, mod: None=None):
        ...

    def __rpow__(self, other: object, mod: None=None):
        ...

    def __sub__(self, other: object):
        ...

    def __rsub__(self, other: object):
        ...

    def __and__(self, other: object):
        ...

    def __rand__(self, other: object):
        ...

    def __or__(self, other: object):
        ...

    def __ror__(self, other: object):
        ...

    def __xor__(self, other: object):
        ...

    def __rxor__(self, other: object):
        ...

    def __lshift__(self, other: object):
        ...

    def __rlshift__(self, other: object):
        ...

    def __rshift__(self, other: object):
        ...

    def __rrshift__(self, other: object):
        ...

class NullArray(Array):
    ...

class BooleanArray(Array):

    @property
    def false_count(self):
        ...

    @property
    def true_count(self):
        ...

class NumericArray(Array):
    ...

class IntegerArray(NumericArray):
    ...

class FloatingPointArray(NumericArray):
    ...

class Int8Array(IntegerArray):
    ...

class UInt8Array(IntegerArray):
    ...

class Int16Array(IntegerArray):
    ...

class UInt16Array(IntegerArray):
    ...

class Int32Array(IntegerArray):
    ...

class UInt32Array(IntegerArray):
    ...

class Int64Array(IntegerArray):
    ...

class UInt64Array(IntegerArray):
    ...

class Date32Array(NumericArray):
    ...

class Date64Array(NumericArray):
    ...

class TimestampArray(NumericArray):
    ...

class Time32Array(NumericArray):
    ...

class Time64Array(NumericArray):
    ...

class DurationArray(NumericArray):
    ...

class MonthDayNanoIntervalArray(Array):

    def to_pylist(self, *, maps_as_pydicts: str | None=None) -> list:
        ...

class HalfFloatArray(FloatingPointArray):
    ...

class FloatArray(FloatingPointArray):
    ...

class DoubleArray(FloatingPointArray):
    ...

class FixedSizeBinaryArray(Array):
    ...

class Decima32Array(FixedSizeBinaryArray):
    ...

class Decimal64Array(FixedSizeBinaryArray):
    ...

class Decimal128Array(FixedSizeBinaryArray):
    ...

class Decimal256Array(FixedSizeBinaryArray):
    ...

class BaseListArray(Array):

    def flatten(self, recursive: bool=False) -> Array:
        ...

    def value_parent_indices(self):
        ...

    def value_lengths(self):
        ...

class ListArray(BaseListArray):

    @staticmethod
    def from_arrays(offsets: Array, values: Array, type: DataType | None=None, pool: MemoryPool | None=None, mask: Array | None=None) -> Array:
        ...

    @property
    def values(self) -> Array:
        ...

    @property
    def offsets(self) -> Array:
        ...

class LargeListArray(BaseListArray):

    @staticmethod
    def from_arrays(offsets: Array, values: Array, type: DataType | None=None, pool: MemoryPool | None=None, mask: Array | None=None) -> Array:
        ...

    @property
    def values(self) -> Array:
        ...

    @property
    def offsets(self) -> Array:
        ...

class ListViewArray(BaseListArray):

    @staticmethod
    def from_arrays(offsets: Array, sizes: Array, values: Array, type: DataType | None=None, pool: MemoryPool | None=None, mask: Array | None=None) -> Array:
        ...

    @property
    def values(self) -> Array:
        ...

    @property
    def offsets(self) -> Array:
        ...

    @property
    def sizes(self) -> Array:
        ...

class LargeListViewArray(BaseListArray):

    @staticmethod
    def from_arrays(offsets: Array, sizes: Array, values: Array, type: DataType | None=None, pool: MemoryPool | None=None, mask: Array | None=None) -> Array:
        ...

    @property
    def values(self) -> Array:
        ...

    @property
    def offsets(self) -> Array:
        ...

    @property
    def sizes(self) -> Array:
        ...

class MapArray(ListArray):

    @staticmethod
    def from_arrays(offsets, keys, items, type: DataType | None=None, pool: MemoryPool | None=None, mask: Array | None=None) -> Array:
        ...

    @property
    def keys(self) -> Array:
        ...

    @property
    def items(self) -> Array:
        ...

class FixedSizeListArray(BaseListArray):

    @staticmethod
    def from_arrays(values: Array, list_size: int | None=None, type: DataType | None=None, mask: Array | None=None) -> Array:
        ...

    @property
    def values(self) -> Array:
        ...

class UnionArray(Array):

    def child(self, pos: int) -> Field:
        ...

    def field(self, pos: int) -> Array:
        ...

    @property
    def type_codes(self) -> Array:
        ...

    @property
    def offsets(self) -> Array:
        ...

    @staticmethod
    def from_dense(types: Array, value_offsets: Array, children: list[Any], field_names: list[Any] | None=None, type_codes: list[Any] | None=None) -> Array:
        ...

    @staticmethod
    def from_sparse(types: Array, children: list[Any], field_names: list[Any] | None=None, type_codes: list[Any] | None=None) -> Array:
        ...

class StringArray(Array):

    @staticmethod
    def from_buffers(length: int, value_offsets: Buffer, data: Buffer, null_bitmap: Buffer | None=None, null_count: int=-1, offset: int=0) -> Array:
        ...

class LargeStringArray(Array):

    @staticmethod
    def from_buffers(length: int, value_offsets: Buffer, data: Buffer, null_bitmap: Buffer | None=None, null_count: int=-1, offset: int=0) -> Array:
        ...

class StringViewArray(Array):
    ...

class BinaryArray(Array):

    @property
    def total_values_length(self):
        ...

class LargeBinaryArray(Array):

    @property
    def total_values_length(self):
        ...

class BinaryViewArray(Array):
    ...

class DictionaryArray(Array):

    def dictionary_encode(self) -> DictionaryArray:
        ...

    def dictionary_decode(self):
        ...

    @property
    def dictionary(self):
        ...

    @property
    def indices(self):
        ...

    @staticmethod
    def from_buffers(type: DataType, length: int, buffers, dictionary: Array, null_count: int=-1, offset: int=0) -> Array:
        ...

    @staticmethod
    def from_arrays(indices, dictionary, mask=None, ordered: bool=False, from_pandas: bool=False, safe: bool=True, memory_pool: MemoryPool | None=None) -> Array:
        ...

class StructArray(Array):

    def field(self, index) -> Array:
        ...

    def _flattened_field(self, index, memory_pool: MemoryPool | None=None) -> Array:
        ...

    def flatten(self, memory_pool: MemoryPool | None=None) -> list:
        ...

    @staticmethod
    def from_arrays(arrays: Sequence[Array], names: list[str] | None=None, fields: list[Field] | None=None, mask=None, memory_pool: MemoryPool | None=None, type: StructType | None=None) -> StructArray:
        ...

    def sort(self, order: str='ascending', null_placement: str='at_end', by: str | None=None, **kwargs) -> StructArray:
        ...

class RunEndEncodedArray(Array):

    @staticmethod
    def _from_arrays(type, allow_none_for_type, logical_length, run_ends, values, logical_offset) -> Array:
        ...

    @staticmethod
    def from_arrays(run_ends, values: Array, type: DataType | None=None) -> RunEndEncodedArray:
        ...

    @staticmethod
    def from_buffers(type: DataType, length: int, buffers: list[Buffer], null_count: int=-1, offset: int=0, children: list[Array] | None=None) -> RunEndEncodedArray:
        ...

    @property
    def run_ends(self) -> Array:
        ...

    @property
    def values(self) -> Array:
        ...

    def find_physical_offset(self):
        ...

    def find_physical_length(self):
        ...

class ExtensionArray(Array):

    @property
    def storage(self) -> Array:
        ...

    @staticmethod
    def from_storage(typ: BaseExtensionType, storage: Array) -> Array:
        ...

class JsonArray(ExtensionArray):
    ...

class UuidArray(ExtensionArray):
    ...

class FixedShapeTensorArray(ExtensionArray):

    def to_numpy_ndarray(self):
        ...

    @staticmethod
    def from_tensor(tensor: Tensor) -> Array:
        ...

    @staticmethod
    def from_numpy_ndarray(obj, dim_names: tuple | list[str] | None=None) -> ExtensionArray:
        ...

    @staticmethod
    def from_dlpack(x: object, /, *, device=None, copy: bool | None=None) -> FixedShapeTensorArray:
        ...

    def __dlpack__(self, *, stream=None, max_version=None, dl_device=None, copy=None):
        ...

class OpaqueArray(ExtensionArray):
    ...

class Bool8Array(ExtensionArray):

    def to_numpy(self, zero_copy_only: bool=True, writable: bool=False):
        ...

    @staticmethod
    def from_storage(storage: Int8Array) -> ExtensionArray:
        ...

    @staticmethod
    def from_numpy(obj) -> Bool8Array:
        ...

class StringBuilder(_Weakrefable):

    def __init__(self, memory_pool: MemoryPool | None=None):
        ...

    def append(self, value) -> None:
        ...

    def append_values(self, values) -> None:
        ...

    def finish(self) -> Array:
        ...

    @property
    def null_count(self):
        ...

    def __len__(self):
        ...

class StringViewBuilder(_Weakrefable):

    def __init__(self, memory_pool: MemoryPool | None=None):
        ...

    def append(self, value) -> None:
        ...

    def append_values(self, values) -> None:
        ...

    def finish(self) -> Array:
        ...

    @property
    def null_count(self):
        ...

    def __len__(self):
        ...

class ChunkedArray(_PandasConvertible):
    _name: object

    def __init__(self):
        ...

    def __reduce__(self) -> tuple:
        ...

    @property
    def data(self) -> ChunkedArray:
        ...

    @property
    def type(self) -> DataType:
        ...

    def length(self):
        ...

    def __len__(self):
        ...

    def __repr__(self) -> str:
        ...

    def to_string(self, *, indent: int=0, window: int=5, container_window: int=2, skip_new_lines: bool=False, element_size_limit: int=100) -> str:
        ...

    def format(self, **kwargs) -> str:
        ...

    def __str__(self):
        ...

    def validate(self, *, full: bool=False) -> None:
        ...

    @property
    def null_count(self) -> int:
        ...

    @property
    def nbytes(self):
        ...

    def get_total_buffer_size(self) -> int:
        ...

    def __sizeof__(self):
        ...

    def __iter__(self) -> Iterator[Any]:
        ...

    def __getitem__(self, key) -> Scalar | ChunkedArray:
        ...

    def is_null(self, *, nan_is_null: bool=False):
        ...

    def is_nan(self):
        ...

    def is_valid(self):
        ...

    def __eq__(self, other):
        ...

    def fill_null(self, fill_value: Any) -> Array | ChunkedArray:
        ...

    def equals(self, other: ChunkedArray) -> bool:
        ...

    def _to_pandas(self, options, types_mapper=None, **kwargs):
        ...

    def to_numpy(self, zero_copy_only: bool=False):
        ...

    def __array__(self, dtype=None, copy=None):
        ...

    def cast(self, target_type: object | None=None, safe: bool | None=None, options: pyarrow.compute.CastOptions | None=None) -> Array | ChunkedArray:
        ...

    def dictionary_encode(self, null_encoding: str='mask') -> ChunkedArray:
        ...

    def flatten(self, memory_pool: MemoryPool | None=None) -> list:
        ...

    def combine_chunks(self, memory_pool: MemoryPool | None=None) -> Array:
        ...

    def unique(self) -> Array:
        ...

    def value_counts(self):
        ...

    def slice(self, offset: int | Scalar=0, length: int | Scalar | None=None) -> ChunkedArray:
        ...

    def filter(self, mask, null_selection_behavior: object='drop') -> Array | ChunkedArray:
        ...

    def index(self, value: Scalar | object, start: int | None=None, end: int | None=None, *, memory_pool: MemoryPool | None=None) -> Int64Scalar:
        ...

    def take(self, indices: object) -> Array | ChunkedArray:
        ...

    def drop_null(self):
        ...

    def sort(self, order: str='ascending', null_placement: str='at_end', **kwargs) -> ChunkedArray:
        ...

    def unify_dictionaries(self, memory_pool: MemoryPool | None=None) -> ChunkedArray:
        ...

    @property
    def num_chunks(self) -> int:
        ...

    def chunk(self, i: int) -> Array:
        ...

    @property
    def chunks(self) -> list:
        ...

    def iterchunks(self) -> Iterator[Any]:
        ...

    def to_pylist(self, *, maps_as_pydicts: str | None=None) -> list:
        ...

    def __arrow_c_stream__(self, requested_schema=None):
        ...

    @staticmethod
    def _import_from_c_capsule(stream) -> ChunkedArray:
        ...

    @property
    def is_cpu(self):
        ...

    def _assert_cpu(self) -> None:
        ...

class _Tabular(_PandasConvertible):

    def __init__(self):
        ...

    def __array__(self, dtype=None, copy=None):
        ...

    def __dataframe__(self, nan_as_null: bool=False, allow_copy: bool=True):
        ...

    def __eq__(self, other):
        ...

    def __getitem__(self, key):
        ...

    def __len__(self):
        ...

    def __repr__(self):
        ...

    def _column(self, i: int):
        ...

    def _ensure_integer_index(self, i):
        ...

    def _is_initialized(self):
        ...

    def column(self, i: int | str) -> Array | ChunkedArray:
        ...

    @property
    def column_names(self) -> list:
        ...

    @property
    def columns(self) -> list:
        ...

    def drop_null(self) -> Table | RecordBatch:
        ...

    def field(self, i: int | str) -> Field:
        ...

    @classmethod
    def from_pydict(cls, mapping: dict | Mapping[Any, Any], schema: Schema | None=None, metadata: dict | Mapping[Any, Any] | None=None) -> Table | RecordBatch:
        ...

    @classmethod
    def from_pylist(cls, mapping, schema: Schema | None=None, metadata: dict | Mapping[Any, Any] | None=None) -> Table | RecordBatch:
        ...

    def itercolumns(self) -> Iterator[Any]:
        ...

    @property
    def num_columns(self):
        ...

    @property
    def num_rows(self):
        ...

    @property
    def shape(self) -> tuple:
        ...

    @property
    def schema(self):
        ...

    def sort_by(self, sorting, **kwargs) -> Table | RecordBatch:
        ...

    def take(self, indices: object) -> Table | RecordBatch:
        ...

    def filter(self, mask, null_selection_behavior: object='drop') -> Table | RecordBatch:
        ...

    def to_pydict(self, *, maps_as_pydicts: str | None=None) -> dict:
        ...

    def to_pylist(self, *, maps_as_pydicts: str | None=None) -> list:
        ...

    def to_string(self, *, show_metadata: bool=False, preview_cols: int=0) -> str:
        ...

    def remove_column(self, i: int):
        ...

    def drop_columns(self, columns: str | list[str]) -> _Tabular:
        ...

    def add_column(self, i: int, field_, column):
        ...

    def append_column(self, field_: str | Field, column) -> Table | RecordBatch:
        ...

class RecordBatch(_Tabular):

    def __init__(self):
        ...

    def _is_initialized(self) -> bool:
        ...

    def __reduce__(self) -> tuple:
        ...

    def validate(self, *, full: bool=False) -> None:
        ...

    def replace_schema_metadata(self, metadata: dict | None=None) -> RecordBatch:
        ...

    @property
    def num_columns(self) -> int:
        ...

    @property
    def num_rows(self) -> int:
        ...

    @property
    def schema(self) -> Schema:
        ...

    def _column(self, i: int) -> Array:
        ...

    @property
    def nbytes(self):
        ...

    def get_total_buffer_size(self) -> int:
        ...

    def __sizeof__(self):
        ...

    def add_column(self, i: int, field_: str | Field, column) -> RecordBatch:
        ...

    def remove_column(self, i: int) -> RecordBatch:
        ...

    def set_column(self, i: int, field_: str | Field, column) -> RecordBatch:
        ...

    def rename_columns(self, names) -> RecordBatch:
        ...

    def serialize(self, memory_pool: MemoryPool | None=None) -> Buffer:
        ...

    def slice(self, offset: int | Scalar=0, length: int | Scalar | None=None) -> RecordBatch:
        ...

    def equals(self, other: object, check_metadata: bool=False) -> bool:
        ...

    def select(self, columns: object) -> RecordBatch:
        ...

    def cast(self, target_schema: Schema, safe: bool | None=None, options: pyarrow.compute.CastOptions | None=None) -> RecordBatch:
        ...

    def _to_pandas(self, options, **kwargs):
        ...

    @classmethod
    def from_pandas(cls, df, schema: Schema | None=None, preserve_index: bool | None=None, nthreads: int | None=None, columns: list | None=None) -> RecordBatch | Self:
        ...

    @staticmethod
    def from_arrays(arrays: list[Any], names: list[str] | None=None, schema: Schema | None=None, metadata: dict | Mapping[Any, Any] | None=None) -> RecordBatch:
        ...

    @staticmethod
    def from_struct_array(struct_array: StructArray) -> RecordBatch:
        ...

    def to_struct_array(self) -> Array:
        ...

    def to_tensor(self, null_to_nan: bool=False, row_major: bool=True, memory_pool: MemoryPool | None=None) -> Tensor:
        ...

    def copy_to(self, destination: MemoryManager | Device) -> RecordBatch:
        ...

    def _export_to_c(self, out_ptr, out_schema_ptr: int=0) -> None:
        ...

    @staticmethod
    def _import_from_c(in_ptr, schema) -> RecordBatch:
        ...

    def __arrow_c_array__(self, requested_schema=None) -> tuple:
        ...

    def __arrow_c_stream__(self, requested_schema=None):
        ...

    @staticmethod
    def _import_from_c_capsule(schema_capsule, array_capsule) -> RecordBatch:
        ...

    def _export_to_c_device(self, out_ptr, out_schema_ptr: int=0) -> None:
        ...

    @staticmethod
    def _import_from_c_device(in_ptr, schema) -> RecordBatch:
        ...

    def __arrow_c_device_array__(self, requested_schema=None, **kwargs) -> tuple:
        ...

    @staticmethod
    def _import_from_c_device_capsule(schema_capsule, array_capsule) -> RecordBatch:
        ...

    @property
    def device_type(self) -> DeviceAllocationType:
        ...

    @property
    def is_cpu(self) -> bool:
        ...

class Table(_Tabular):

    def __init__(self):
        ...

    def _is_initialized(self) -> bool:
        ...

    def validate(self, *, full: bool=False) -> None:
        ...

    def __reduce__(self) -> tuple:
        ...

    def slice(self, offset: int | Scalar=0, length: int | Scalar | None=None) -> Table:
        ...

    def select(self, columns: object) -> Table:
        ...

    def replace_schema_metadata(self, metadata: dict | None=None) -> Table:
        ...

    def flatten(self, memory_pool: MemoryPool | None=None) -> Table:
        ...

    def combine_chunks(self, memory_pool: MemoryPool | None=None) -> Table:
        ...

    def unify_dictionaries(self, memory_pool: MemoryPool | None=None) -> Table:
        ...

    def equals(self, other: Table, check_metadata: bool=False) -> bool:
        ...

    def cast(self, target_schema: Schema, safe: bool | None=None, options: pyarrow.compute.CastOptions | None=None) -> Table:
        ...

    @classmethod
    def from_pandas(cls, df, schema: Schema | None=None, preserve_index: bool | None=None, nthreads: int | None=None, columns: list | None=None, safe: bool=True) -> Table | Self:
        ...

    @staticmethod
    def from_arrays(arrays: list[Array] | ChunkedArray, names: list[str] | None=None, schema: Schema | None=None, metadata: dict | Mapping[Any, Any] | None=None) -> Table:
        ...

    @staticmethod
    def from_struct_array(struct_array: StructArray | ChunkedArray) -> Table:
        ...

    def to_struct_array(self, max_chunksize: int | None=None) -> ChunkedArray:
        ...

    @staticmethod
    def from_batches(batches: Sequence[Any] | Iterator[RecordBatch], schema: Schema | None=None) -> Table:
        ...

    def to_batches(self, max_chunksize: int | None=None) -> list[RecordBatch]:
        ...

    def to_tensor(self, null_to_nan: bool=False, row_major: bool=True, memory_pool: MemoryPool | None=None) -> Tensor:
        ...

    def to_reader(self, max_chunksize: int | None=None) -> RecordBatchReader:
        ...

    def _to_pandas(self, options, categories=None, ignore_metadata: bool=False, types_mapper=None):
        ...

    @property
    def schema(self) -> Schema:
        ...

    def _column(self, i: int) -> ChunkedArray:
        ...

    @property
    def num_columns(self) -> int:
        ...

    @property
    def num_rows(self) -> int:
        ...

    @property
    def nbytes(self):
        ...

    def get_total_buffer_size(self) -> int:
        ...

    def __sizeof__(self):
        ...

    def add_column(self, i: int, field_: str | Field, column) -> Table:
        ...

    def remove_column(self, i: int) -> Table:
        ...

    def set_column(self, i: int, field_: str | Field, column) -> Table:
        ...

    def rename_columns(self, names) -> Table:
        ...

    def drop(self, columns: str | list[str]) -> Table:
        ...

    def group_by(self, keys: str | list[str], use_threads: bool=True) -> TableGroupBy:
        ...

    def join(self, right_table: Table, keys: str | list[str], right_keys: str | list[str] | None=None, join_type: str='left outer', left_suffix: str | None=None, right_suffix: str | None=None, coalesce_keys: bool=True, use_threads: bool=True, filter_expression: pyarrow.compute.Expression | None=None) -> Table:
        ...

    def join_asof(self, right_table: Table, on: str, by: str | list[str], tolerance: int, right_on: str | list[str] | None=None, right_by: str | list[str] | None=None) -> Table:
        ...

    def __arrow_c_stream__(self, requested_schema=None):
        ...

    @property
    def is_cpu(self):
        ...

class TableGroupBy:

    def __init__(self, table, keys, use_threads: bool=True):
        ...

    def aggregate(self, aggregations) -> Table:
        ...

class Tensor(_Weakrefable):
    type: DataType
    _ssize_t_shape: bytes
    _ssize_t_strides: bytes

    def __init__(self):
        ...

    def _make_shape_or_strides_buffer(self, values):
        ...

    def __repr__(self) -> str:
        ...

    @staticmethod
    def from_numpy(obj, dim_names: list | None=None) -> Tensor:
        ...

    def to_numpy(self):
        ...

    def equals(self, other: Tensor):
        ...

    def __eq__(self, other):
        ...

    def dim_name(self, i: int) -> str:
        ...

    @property
    def dim_names(self) -> list:
        ...

    @property
    def is_mutable(self):
        ...

    @property
    def is_contiguous(self):
        ...

    @property
    def ndim(self):
        ...

    @property
    def size(self):
        ...

    @property
    def shape(self) -> tuple:
        ...

    @property
    def strides(self) -> tuple:
        ...

    @staticmethod
    def from_dlpack(x: object, /, *, device=None, copy: bool | None=None) -> Tensor:
        ...

    def __dlpack__(self, *, stream: int | None=None, max_version=None, dl_device=None, copy: bool | None=None):
        ...

    def __dlpack_device__(self) -> tuple:
        ...

class SparseCOOTensor(_Weakrefable):
    type: DataType

    def __init__(self):
        ...

    def __repr__(self) -> str:
        ...

    @classmethod
    def from_dense_numpy(cls, obj, dim_names: list[str] | None=None) -> Self:
        ...

    @staticmethod
    def from_numpy(data, coords, shape: tuple, dim_names: list | None=None) -> SparseCOOTensor:
        ...

    @staticmethod
    def from_scipy(obj, dim_names: list | None=None) -> SparseCOOTensor:
        ...

    @staticmethod
    def from_pydata_sparse(obj, dim_names: list | None=None) -> SparseCOOTensor:
        ...

    @staticmethod
    def from_tensor(obj: Tensor) -> SparseCOOTensor:
        ...

    def to_numpy(self) -> tuple:
        ...

    def to_scipy(self):
        ...

    def to_pydata_sparse(self):
        ...

    def to_tensor(self) -> Tensor:
        ...

    def equals(self, other: SparseCOOTensor):
        ...

    def __eq__(self, other):
        ...

    @property
    def is_mutable(self):
        ...

    @property
    def ndim(self):
        ...

    @property
    def shape(self) -> tuple:
        ...

    @property
    def size(self):
        ...

    def dim_name(self, i: int) -> str:
        ...

    @property
    def dim_names(self) -> tuple:
        ...

    @property
    def non_zero_length(self):
        ...

    @property
    def has_canonical_format(self):
        ...

class SparseCSRMatrix(_Weakrefable):
    type: DataType

    def __init__(self):
        ...

    def __repr__(self) -> str:
        ...

    @classmethod
    def from_dense_numpy(cls, obj, dim_names: list | None=None) -> Self:
        ...

    @staticmethod
    def from_numpy(data, indptr, indices, shape: tuple, dim_names: list | None=None) -> SparseCSRMatrix:
        ...

    @staticmethod
    def from_scipy(obj, dim_names: list | None=None) -> SparseCSRMatrix:
        ...

    @staticmethod
    def from_tensor(obj: Tensor) -> SparseCSRMatrix:
        ...

    def to_numpy(self) -> tuple:
        ...

    def to_scipy(self):
        ...

    def to_tensor(self) -> Tensor:
        ...

    def equals(self, other: SparseCSRMatrix):
        ...

    def __eq__(self, other):
        ...

    @property
    def is_mutable(self):
        ...

    @property
    def ndim(self):
        ...

    @property
    def shape(self) -> tuple:
        ...

    @property
    def size(self):
        ...

    def dim_name(self, i: int) -> str:
        ...

    @property
    def dim_names(self) -> tuple:
        ...

    @property
    def non_zero_length(self):
        ...

class SparseCSCMatrix(_Weakrefable):
    type: DataType

    def __init__(self):
        ...

    def __repr__(self) -> str:
        ...

    @classmethod
    def from_dense_numpy(cls, obj, dim_names: list[str] | None=None) -> Self:
        ...

    @staticmethod
    def from_numpy(data, indptr, indices, shape: tuple, dim_names: list | None=None) -> SparseCSCMatrix:
        ...

    @staticmethod
    def from_scipy(obj, dim_names: list | None=None) -> SparseCSCMatrix:
        ...

    @staticmethod
    def from_tensor(obj: Tensor) -> SparseCSCMatrix:
        ...

    def to_numpy(self) -> tuple:
        ...

    def to_scipy(self):
        ...

    def to_tensor(self) -> Tensor:
        ...

    def equals(self, other: SparseCSCMatrix):
        ...

    def __eq__(self, other):
        ...

    @property
    def is_mutable(self):
        ...

    @property
    def ndim(self):
        ...

    @property
    def shape(self) -> tuple:
        ...

    @property
    def size(self):
        ...

    def dim_name(self, i: int) -> str:
        ...

    @property
    def dim_names(self) -> tuple:
        ...

    @property
    def non_zero_length(self):
        ...

class SparseCSFTensor(_Weakrefable):
    type: DataType

    def __init__(self):
        ...

    def __repr__(self) -> str:
        ...

    @classmethod
    def from_dense_numpy(cls, obj, dim_names: list[str] | None=None) -> Self:
        ...

    @staticmethod
    def from_numpy(data, indptr, indices, shape: tuple, axis_order: list | None=None, dim_names: list | None=None) -> SparseCSFTensor:
        ...

    @staticmethod
    def from_tensor(obj: Tensor) -> SparseCSFTensor:
        ...

    def to_numpy(self) -> tuple:
        ...

    def to_tensor(self) -> Tensor:
        ...

    def equals(self, other: SparseCSFTensor):
        ...

    def __eq__(self, other):
        ...

    @property
    def is_mutable(self):
        ...

    @property
    def ndim(self):
        ...

    @property
    def shape(self) -> tuple:
        ...

    @property
    def size(self):
        ...

    def dim_name(self, i: int) -> str:
        ...

    @property
    def dim_names(self) -> tuple:
        ...

    @property
    def non_zero_length(self):
        ...

class NativeFile(_Weakrefable):
    _default_chunk_size: int

    def __init__(self):
        ...

    def __enter__(self) -> Self:
        ...

    def __exit__(self, exc_type, exc_value, tb) -> None:
        ...

    def __repr__(self) -> str:
        ...

    @property
    def mode(self) -> str:
        ...

    def readable(self):
        ...

    def writable(self):
        ...

    def seekable(self):
        ...

    def isatty(self) -> bool:
        ...

    def fileno(self):
        ...

    @property
    def closed(self):
        ...

    def close(self) -> None:
        ...

    def _assert_open(self) -> None:
        ...

    def _assert_readable(self) -> None:
        ...

    def _assert_writable(self) -> None:
        ...

    def _assert_seekable(self) -> None:
        ...

    def size(self) -> int:
        ...

    def metadata(self) -> dict:
        ...

    def tell(self) -> int:
        ...

    def seek(self, position: int, whence: int=0) -> int:
        ...

    def flush(self) -> None:
        ...

    def write(self, data) -> int:
        ...

    def read(self, nbytes: int | None=None) -> bytes:
        ...

    def get_stream(self, file_offset: int, nbytes: int) -> NativeFile:
        ...

    def read_at(self, nbytes: int, offset: int) -> bytes:
        ...

    def read1(self, nbytes: int | None=None) -> bytes:
        ...

    def readall(self):
        ...

    def readinto(self, b) -> int:
        ...

    def readline(self, size: int | None=None):
        ...

    def readlines(self, hint: int | None=None):
        ...

    def __iter__(self) -> Self:
        ...

    def __next__(self):
        ...

    def read_buffer(self, nbytes: int | None=None):
        ...

    def truncate(self):
        ...

    def writelines(self, lines: Iterable[Any]) -> None:
        ...

    def download(self, stream_or_path: str | IO[Any], buffer_size: int | None=None):
        ...

    def _download_nothreads(self, stream_or_path, buffer_size=None) -> None:
        ...

    def upload(self, stream: IO[Any], buffer_size: int | None=None):
        ...

    def _upload_nothreads(self, stream, buffer_size=None) -> None:
        ...

class PythonFile(NativeFile):

    def __init__(self, handle, mode=None):
        ...

    def truncate(self, pos: int | None=None) -> None:
        ...

    def readline(self, size: int | None=None):
        ...

    def readlines(self, hint: int | None=None):
        ...

class MemoryMappedFile(NativeFile):

    @staticmethod
    def create(path: str, size: int) -> MemoryMappedFile:
        ...

    def _open(self, path, mode: str='r') -> None:
        ...

    def resize(self, new_size) -> None:
        ...

    def fileno(self):
        ...

class OSFile(NativeFile):

    def __init__(self, path, mode: str='r', memory_pool: MemoryPool | None=None):
        ...

    def fileno(self):
        ...

class FixedSizeBufferWriter(NativeFile):

    def __init__(self, buffer: Buffer):
        ...

    def set_memcopy_threads(self, num_threads: int) -> None:
        ...

    def set_memcopy_blocksize(self, blocksize: int) -> None:
        ...

    def set_memcopy_threshold(self, threshold: int) -> None:
        ...

class Buffer(_Weakrefable):

    def __init__(self):
        ...

    def __len__(self):
        ...

    def __repr__(self) -> str:
        ...

    def _assert_cpu(self) -> None:
        ...

    @property
    def size(self):
        ...

    @property
    def address(self):
        ...

    def hex(self):
        ...

    @property
    def is_mutable(self):
        ...

    @property
    def is_cpu(self):
        ...

    @property
    def device(self) -> Device:
        ...

    @property
    def memory_manager(self) -> MemoryManager:
        ...

    @property
    def device_type(self) -> DeviceAllocationType:
        ...

    @property
    def parent(self) -> None | Buffer:
        ...

    def __getitem__(self, key):
        ...

    def slice(self, offset: int=0, length: int | None=None) -> Buffer:
        ...

    def equals(self, other: Buffer) -> bool:
        ...

    def __eq__(self, other):
        ...

    def __reduce_ex__(self, protocol) -> tuple:
        ...

    def to_pybytes(self):
        ...

class ResizableBuffer(Buffer):

    def resize(self, new_size: int, shrink_to_fit: bool=False) -> None:
        ...

class BufferOutputStream(NativeFile):

    def __init__(self, memory_pool: MemoryPool | None=None):
        ...

    def getvalue(self) -> Buffer:
        ...

class MockOutputStream(NativeFile):

    def __init__(self):
        ...

    def size(self):
        ...

class BufferReader(NativeFile):

    def __init__(self, obj):
        ...

class CompressedInputStream(NativeFile):

    def __init__(self, stream: object, compression: str):
        ...

class CompressedOutputStream(NativeFile):

    def __init__(self, stream: object, compression: str):
        ...

class BufferedInputStream(NativeFile):

    def __init__(self, stream: NativeFile, buffer_size: int, memory_pool: MemoryPool | None=None):
        ...

    def detach(self) -> NativeFile:
        ...

class BufferedOutputStream(NativeFile):

    def __init__(self, stream: NativeFile, buffer_size: int, memory_pool: MemoryPool | None=None):
        ...

    def detach(self) -> NativeFile:
        ...

class TransformInputStream(NativeFile):

    def __init__(self, stream: NativeFile, transform_func):
        ...

class Transcoder:

    def __init__(self, decoder, encoder):
        ...

    def __call__(self, buf):
        ...

class CacheOptions(_Weakrefable):

    def __init__(self, *, hole_size_limit=None, range_size_limit=None, lazy=None, prefetch_limit=None):
        ...

    @property
    def hole_size_limit(self) -> None:
        ...

    @hole_size_limit.setter
    def hole_size_limit(self, hole_size_limit) -> None:
        ...

    @property
    def range_size_limit(self) -> None:
        ...

    @range_size_limit.setter
    def range_size_limit(self, range_size_limit) -> None:
        ...

    @property
    def lazy(self) -> None:
        ...

    @lazy.setter
    def lazy(self, lazy) -> None:
        ...

    @property
    def prefetch_limit(self) -> None:
        ...

    @prefetch_limit.setter
    def prefetch_limit(self, prefetch_limit) -> None:
        ...

    def __eq__(self, other: CacheOptions):
        ...

    @staticmethod
    def from_network_metrics(time_to_first_byte_millis: int, transfer_bandwidth_mib_per_sec: int, ideal_bandwidth_utilization_frac: int | float=0.9, max_ideal_request_size_mib: int=64) -> CacheOptions:
        ...

    @staticmethod
    def _reconstruct(kwargs) -> CacheOptions:
        ...

    def __reduce__(self) -> tuple:
        ...

class Codec(_Weakrefable):

    def __init__(self, compression: str, compression_level=None):
        ...

    @staticmethod
    def detect(path: str | os.PathLike[str]) -> Codec:
        ...

    @staticmethod
    def is_available(compression: str) -> bool:
        ...

    @staticmethod
    def supports_compression_level(compression: str):
        ...

    @staticmethod
    def default_compression_level(compression: str):
        ...

    @staticmethod
    def minimum_compression_level(compression: str):
        ...

    @staticmethod
    def maximum_compression_level(compression: str):
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def compression_level(self):
        ...

    def compress(self, buf: object, asbytes: bool=False, memory_pool: MemoryPool | None=None) -> Buffer | bytes:
        ...

    def decompress(self, buf: object, decompressed_size: int | None=None, asbytes: bool=False, memory_pool: MemoryPool | None=None) -> Buffer | bytes:
        ...

    def __repr__(self) -> str:
        ...

class WriteStats(_WriteStats):
    __slots__ = ()

class ReadStats(_ReadStats):
    __slots__ = ()

class IpcReadOptions(_Weakrefable):
    __slots__ = ()

    def __init__(self, *, ensure_native_endian: bool=True, ensure_alignment: Alignment=Alignment.Any, use_threads: bool=True, included_fields: list[Any] | None=None):
        ...

    @property
    def ensure_native_endian(self) -> None:
        ...

    @ensure_native_endian.setter
    def ensure_native_endian(self, value: bool) -> None:
        ...

    @property
    def ensure_alignment(self) -> None:
        ...

    @ensure_alignment.setter
    def ensure_alignment(self, value: Alignment) -> None:
        ...

    @property
    def use_threads(self) -> None:
        ...

    @use_threads.setter
    def use_threads(self, value: bool) -> None:
        ...

    @property
    def included_fields(self) -> None:
        ...

    @included_fields.setter
    def included_fields(self, value: list[Any]) -> None:
        ...

    def __repr__(self) -> str:
        ...

class IpcWriteOptions(_Weakrefable):
    __slots__ = ()

    def __init__(self, *, metadata_version=MetadataVersion.V5, allow_64bit: bool=False, use_legacy_format: bool=False, compression=None, use_threads: bool=True, emit_dictionary_deltas: bool=False, unify_dictionaries: bool=False):
        ...

    @property
    def allow_64bit(self) -> None:
        ...

    @allow_64bit.setter
    def allow_64bit(self, value: bool) -> None:
        ...

    @property
    def use_legacy_format(self) -> None:
        ...

    @use_legacy_format.setter
    def use_legacy_format(self, value: bool) -> None:
        ...

    @property
    def metadata_version(self) -> None:
        ...

    @metadata_version.setter
    def metadata_version(self, value) -> None:
        ...

    @property
    def compression(self) -> None:
        ...

    @compression.setter
    def compression(self, value) -> None:
        ...

    @property
    def use_threads(self) -> None:
        ...

    @use_threads.setter
    def use_threads(self, value: bool) -> None:
        ...

    @property
    def emit_dictionary_deltas(self) -> None:
        ...

    @emit_dictionary_deltas.setter
    def emit_dictionary_deltas(self, value: bool) -> None:
        ...

    @property
    def unify_dictionaries(self) -> None:
        ...

    @unify_dictionaries.setter
    def unify_dictionaries(self, value: bool) -> None:
        ...

    def __repr__(self) -> str:
        ...

class Message(_Weakrefable):

    def __init__(self):
        ...

    @property
    def type(self) -> str:
        ...

    @property
    def metadata(self) -> Buffer:
        ...

    @property
    def metadata_version(self):
        ...

    @property
    def body(self) -> None | Buffer:
        ...

    def equals(self, other: Message) -> bool:
        ...

    def serialize_to(self, sink: NativeFile, alignment: int=8, memory_pool: MemoryPool | None=None) -> None:
        ...

    def serialize(self, alignment: int=8, memory_pool: MemoryPool | None=None) -> Buffer:
        ...

    def __repr__(self) -> str:
        ...

class MessageReader(_Weakrefable):

    def __init__(self):
        ...

    @staticmethod
    def open_stream(source) -> MessageReader:
        ...

    def __iter__(self) -> Self:
        ...

    def __next__(self):
        ...

    def read_next_message(self) -> Message:
        ...

class _CRecordBatchWriter(_Weakrefable):

    def write(self, table_or_batch) -> None:
        ...

    def write_batch(self, batch: RecordBatch, custom_metadata: Mapping[Any, Any] | KeyValueMetadata | None=None) -> None:
        ...

    def write_table(self, table: Table, max_chunksize: int | None=None) -> None:
        ...

    def close(self) -> None:
        ...

    def __enter__(self) -> Self:
        ...

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        ...

    @property
    def stats(self):
        ...

class _RecordBatchStreamWriter(_CRecordBatchWriter):

    def __init__(self):
        ...

    @property
    def _use_legacy_format(self):
        ...

    @property
    def _metadata_version(self):
        ...

    def _open(self, sink, schema: Schema, options: IpcWriteOptions=IpcWriteOptions()) -> None:
        ...

class _ReadPandasMixin:

    def read_pandas(self, **options):
        ...

class RecordBatchReader(_Weakrefable):
    read_pandas = _ReadPandasMixin.read_pandas

    def __init__(self):
        ...

    def __iter__(self) -> Self:
        ...

    def __next__(self):
        ...

    @property
    def schema(self) -> Schema:
        ...

    def read_next_batch(self) -> RecordBatch:
        ...

    def read_next_batch_with_custom_metadata(self):
        ...

    def iter_batches_with_custom_metadata(self) -> Iterator[Any]:
        ...

    def read_all(self) -> Table:
        ...

    def close(self) -> None:
        ...

    def __enter__(self) -> Self:
        ...

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        ...

    def cast(self, target_schema: Schema) -> RecordBatchReader:
        ...

    def _export_to_c(self, out_ptr) -> None:
        ...

    @staticmethod
    def _import_from_c(in_ptr) -> RecordBatchReader:
        ...

    def __arrow_c_stream__(self, requested_schema=None):
        ...

    @staticmethod
    def _import_from_c_capsule(stream) -> RecordBatchReader:
        ...

    @staticmethod
    def from_stream(data, schema: Schema | None=None) -> RecordBatchReader:
        ...

    @staticmethod
    def from_batches(schema: Schema, batches: Iterable[RecordBatch]) -> RecordBatchReader:
        ...

class _RecordBatchStreamReader(RecordBatchReader):

    def __init__(self):
        ...

    def _open(self, source, options: IpcReadOptions=IpcReadOptions(), memory_pool: MemoryPool | None=None) -> None:
        ...

    @property
    def stats(self):
        ...

class _RecordBatchFileWriter(_RecordBatchStreamWriter):

    def _open(self, sink, schema: Schema, options: IpcWriteOptions=IpcWriteOptions(), metadata=None) -> None:
        ...

class RecordBatchWithMetadata(_RecordBatchWithMetadata):
    __slots__ = ()

class _RecordBatchFileReader(_Weakrefable):
    read_pandas = _ReadPandasMixin.read_pandas
    schema: Schema

    def __init__(self):
        ...

    def _open(self, source, footer_offset=None, options: IpcReadOptions=IpcReadOptions(), memory_pool: MemoryPool | None=None) -> None:
        ...

    @property
    def num_record_batches(self):
        ...

    def count_rows(self) -> int:
        ...

    def get_batch(self, i: int) -> RecordBatch:
        ...
    get_record_batch = get_batch

    def get_batch_with_custom_metadata(self, i: int):
        ...

    def read_all(self) -> Table:
        ...

    def __enter__(self) -> Self:
        ...

    def __exit__(self, exc_type, exc_value, traceback) -> None:
        ...

    @property
    def stats(self):
        ...

    @property
    def metadata(self):
        ...

class Decimal32Array(FixedSizeBinaryArray):
    ...
