# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

from _typeshed import Incomplete
from pyarrow.lib import _pandas_api as _pandas_api, frombytes as frombytes, is_threading_enabled as is_threading_enabled

_logical_type_map: Incomplete
_numpy_logical_type_map: Incomplete
_pandas_logical_type_map: Incomplete

def get_logical_type_map(): ...
def get_logical_type(arrow_type): ...
def get_numpy_logical_type_map(): ...
def get_logical_type_from_numpy(pandas_collection): ...
def get_extension_dtype_info(column): ...
def get_column_metadata(column, name, arrow_type, field_name): ...
def construct_metadata(columns_to_convert, df, column_names, index_levels, index_descriptors, preserve_index, types, column_field_names=None): ...
def _get_simple_index_descriptor(level, name): ...
def _column_name_to_strings(name): ...
def _index_level_name(index, i, column_names): ...
def _get_columns_to_convert(df, schema, preserve_index, columns): ...
def _get_columns_to_convert_given_schema(df, schema, preserve_index): ...
def _get_index_level(df, name): ...
def _level_name(name): ...
def _get_range_index_descriptor(level): ...
def _get_index_level_values(index): ...
def _resolve_columns_of_interest(df, schema, columns): ...
def dataframe_to_types(df, preserve_index, columns=None): ...
def dataframe_to_arrays(df, schema, preserve_index, nthreads: int = 1, columns=None, safe: bool = True): ...
def get_datetimetz_type(values, dtype, type_): ...
def _reconstruct_block(item, columns=None, extension_columns=None, return_block: bool = True): ...
def make_datetimetz(unit, tz): ...
def table_to_dataframe(options, table, categories=None, ignore_metadata: bool = False, types_mapper=None): ...

_pandas_supported_numpy_types: Incomplete

def _get_extension_dtypes(table, columns_metadata, types_mapper, options, categories): ...
def _check_data_column_metadata_consistency(all_columns) -> None: ...
def _deserialize_column_index(block_table, all_columns, column_indexes): ...
def _reconstruct_index(table, index_descriptors, all_columns, types_mapper=None): ...
def _extract_index_level(table, result_table, field_name, field_name_to_metadata, types_mapper=None): ...
def _backwards_compatible_index_name(raw_name, logical_name): ...
def _is_generated_index_name(name): ...
def get_pandas_logical_type_map(): ...
def _pandas_type_to_numpy_type(pandas_type): ...
def _reconstruct_columns_from_metadata(columns, column_indexes): ...
def _add_any_metadata(table, pandas_metadata): ...
def make_tz_aware(series, tz): ...
