# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

from pyarrow.lib import DataType, Decimal128Type, Decimal256Type, Decimal32Type, Decimal64Type, DenseUnionType, DictionaryType, DurationType, FixedSizeBinaryType, FixedSizeListType, LargeListType, LargeListViewType, ListType, ListViewType, MapType, RunEndEncodedType, SparseUnionType, StructType, Time32Type, Time64Type, TimestampType, UuidType
from pyarrow.tests.test_extension_type import PeriodType, PeriodTypeWithClass, PeriodTypeWithToPandasDtype
from pyarrow.tests.test_pandas import DummyExtensionType, MyCustomIntegerType
from typing import Union
import os
import re
import pyarrow
from typing import Any, Callable, IO, Iterable, Iterator, Literal, Mapping, NamedTuple, Self, Sequence
from _typeshed import Incomplete
from enum import IntEnum
from pyarrow.lib import is_boolean_value as is_boolean_value, is_float_value as is_float_value, is_integer_value as is_integer_value
from pyarrow.util import doc as doc
_SIGNED_INTEGER_TYPES: Incomplete
_UNSIGNED_INTEGER_TYPES: Incomplete
_INTEGER_TYPES: set[Incomplete]
_FLOATING_TYPES: Incomplete
_DECIMAL_TYPES: Incomplete
_DATE_TYPES: Incomplete
_TIME_TYPES: Incomplete
_INTERVAL_TYPES: Incomplete
_TEMPORAL_TYPES: Incomplete
_UNION_TYPES: Incomplete

def is_null(t: pyarrow.DataType) -> bool:
    ...

def is_boolean(t: pyarrow.DataType) -> bool:
    ...

def is_integer(t: pyarrow.DataType) -> bool:
    ...

def is_signed_integer(t: pyarrow.DataType) -> bool:
    ...

def is_unsigned_integer(t: pyarrow.DataType) -> bool:
    ...

def is_int8(t: pyarrow.DataType) -> bool:
    ...

def is_int16(t: pyarrow.DataType) -> bool:
    ...

def is_int32(t: pyarrow.DataType) -> bool:
    ...

def is_int64(t: pyarrow.DataType) -> bool:
    ...

def is_uint8(t: pyarrow.DataType) -> bool:
    ...

def is_uint16(t: pyarrow.DataType) -> bool:
    ...

def is_uint32(t: pyarrow.DataType) -> bool:
    ...

def is_uint64(t: pyarrow.DataType) -> bool:
    ...

def is_floating(t: pyarrow.DataType) -> bool:
    ...

def is_float16(t: pyarrow.DataType) -> bool:
    ...

def is_float32(t: pyarrow.DataType) -> bool:
    ...

def is_float64(t: pyarrow.DataType) -> bool:
    ...

def is_list(t: pyarrow.DataType) -> bool:
    ...

def is_large_list(t: pyarrow.DataType) -> bool:
    ...

def is_fixed_size_list(t: pyarrow.DataType) -> bool:
    ...

def is_list_view(t: pyarrow.DataType) -> bool:
    ...

def is_large_list_view(t: pyarrow.DataType) -> bool:
    ...

def is_struct(t: pyarrow.DataType) -> bool:
    ...

def is_union(t: pyarrow.DataType) -> bool:
    ...

def is_nested(t: pyarrow.DataType) -> bool:
    ...

def is_run_end_encoded(t: pyarrow.DataType) -> bool:
    ...

def is_temporal(t: pyarrow.DataType) -> bool:
    ...

def is_timestamp(t: pyarrow.DataType) -> bool:
    ...

def is_duration(t: pyarrow.DataType) -> bool:
    ...

def is_time(t: pyarrow.DataType) -> bool:
    ...

def is_time32(t: pyarrow.DataType) -> bool:
    ...

def is_time64(t: pyarrow.DataType) -> bool:
    ...

def is_binary(t: pyarrow.DataType) -> bool:
    ...

def is_large_binary(t: pyarrow.DataType) -> bool:
    ...

def is_unicode(t: pyarrow.DataType) -> bool:
    ...

def is_string(t: pyarrow.DataType) -> bool:
    ...

def is_large_unicode(t: pyarrow.DataType):
    ...

def is_large_string(t: pyarrow.DataType) -> bool:
    ...

def is_fixed_size_binary(t: pyarrow.DataType) -> bool:
    ...

def is_binary_view(t: pyarrow.DataType) -> bool:
    ...

def is_string_view(t: pyarrow.DataType) -> bool:
    ...

def is_date(t: pyarrow.DataType) -> bool:
    ...

def is_date32(t: pyarrow.DataType) -> bool:
    ...

def is_date64(t: pyarrow.DataType) -> bool:
    ...

def is_map(t: pyarrow.DataType) -> bool:
    ...

def is_decimal(t: pyarrow.DataType) -> bool:
    ...

def is_decimal32(t: pyarrow.DataType) -> bool:
    ...

def is_decimal64(t: pyarrow.DataType) -> bool:
    ...

def is_decimal128(t: pyarrow.DataType) -> bool:
    ...

def is_decimal256(t: pyarrow.DataType) -> bool:
    ...

def is_dictionary(t: pyarrow.DataType) -> bool:
    ...

def is_interval(t: pyarrow.DataType) -> bool:
    ...

def is_primitive(t: pyarrow.DataType) -> bool:
    ...

class TypesEnum(IntEnum):
    NA = ...
    BOOL = ...
    INT8 = ...
    INT16 = ...
    INT32 = ...
    INT64 = ...
    UINT8 = ...
    UINT16 = ...
    UINT32 = ...
    UINT64 = ...
    HALF_FLOAT = ...
    FLOAT = ...
    DOUBLE = ...
    BINARY = ...
    BINARY_VIEW = ...
    LARGE_BINARY = ...
    STRING = ...
    STRING_VIEW = ...
    LARGE_STRING = ...
    FIXED_SIZE_BINARY = ...
    DECIMAL32 = ...
    DECIMAL64 = ...
    DECIMAL128 = ...
    DECIMAL256 = ...
    LIST = ...
    LARGE_LIST = ...
    LIST_VIEW = ...
    LARGE_LIST_VIEW = ...
    MAP = ...
    FIXED_SIZE_LIST = ...
    STRUCT = ...
    SPARSE_UNION = ...
    DENSE_UNION = ...
    RUN_END_ENCODED = ...
    DATE32 = ...
    DATE64 = ...
    TIME32 = ...
    TIME64 = ...
    TIMESTAMP = ...
    INTERVAL_MONTHS = ...
    INTERVAL_DAY_TIME = ...
    INTERVAL_MONTH_DAY_NANO = ...
    DURATION = ...
    DICTIONARY = ...
