# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

from _typeshed import Incomplete
from enum import IntEnum
from pyarrow.lib import is_boolean_value as is_boolean_value, is_float_value as is_float_value, is_integer_value as is_integer_value
from pyarrow.util import doc as doc

_SIGNED_INTEGER_TYPES: Incomplete
_UNSIGNED_INTEGER_TYPES: Incomplete
_INTEGER_TYPES = _SIGNED_INTEGER_TYPES | _UNSIGNED_INTEGER_TYPES
_FLOATING_TYPES: Incomplete
_DECIMAL_TYPES: Incomplete
_DATE_TYPES: Incomplete
_TIME_TYPES: Incomplete
_INTERVAL_TYPES: Incomplete
_TEMPORAL_TYPES: Incomplete
_UNION_TYPES: Incomplete

class TypesEnum(IntEnum):
    NA = ...
    BOOL = ...
    INT8 = ...
    INT16 = ...
    INT32 = ...
    INT64 = ...
    UINT8 = ...
    UINT16 = ...
    UINT32 = ...
    UINT64 = ...
    HALF_FLOAT = ...
    FLOAT = ...
    DOUBLE = ...
    BINARY = ...
    BINARY_VIEW = ...
    LARGE_BINARY = ...
    STRING = ...
    STRING_VIEW = ...
    LARGE_STRING = ...
    FIXED_SIZE_BINARY = ...
    DECIMAL32 = ...
    DECIMAL64 = ...
    DECIMAL128 = ...
    DECIMAL256 = ...
    LIST = ...
    LARGE_LIST = ...
    LIST_VIEW = ...
    LARGE_LIST_VIEW = ...
    MAP = ...
    FIXED_SIZE_LIST = ...
    STRUCT = ...
    SPARSE_UNION = ...
    DENSE_UNION = ...
    RUN_END_ENCODED = ...
    DATE32 = ...
    DATE64 = ...
    TIME32 = ...
    TIME64 = ...
    TIMESTAMP = ...
    INTERVAL_MONTHS = ...
    INTERVAL_DAY_TIME = ...
    INTERVAL_MONTH_DAY_NANO = ...
    DURATION = ...
    DICTIONARY = ...

def is_null(t): ...
def is_boolean(t): ...
def is_integer(t): ...
def is_signed_integer(t): ...
def is_unsigned_integer(t): ...
def is_int8(t): ...
def is_int16(t): ...
def is_int32(t): ...
def is_int64(t): ...
def is_uint8(t): ...
def is_uint16(t): ...
def is_uint32(t): ...
def is_uint64(t): ...
def is_floating(t): ...
def is_float16(t): ...
def is_float32(t): ...
def is_float64(t): ...
def is_list(t): ...
def is_large_list(t): ...
def is_fixed_size_list(t): ...
def is_list_view(t): ...
def is_large_list_view(t): ...
def is_struct(t): ...
def is_union(t): ...
def is_nested(t): ...
def is_run_end_encoded(t): ...
def is_temporal(t): ...
def is_timestamp(t): ...
def is_duration(t): ...
def is_time(t): ...
def is_time32(t): ...
def is_time64(t): ...
def is_binary(t): ...
def is_large_binary(t): ...
def is_unicode(t): ...
def is_string(t): ...
def is_large_unicode(t): ...
def is_large_string(t): ...
def is_fixed_size_binary(t): ...
def is_binary_view(t): ...
def is_string_view(t): ...
def is_date(t): ...
def is_date32(t): ...
def is_date64(t): ...
def is_map(t): ...
def is_decimal(t): ...
def is_decimal32(t): ...
def is_decimal64(t): ...
def is_decimal128(t): ...
def is_decimal256(t): ...
def is_dictionary(t): ...
def is_interval(t): ...
def is_primitive(t): ...
