_DEPR_MSG: str

def doc(*docstrings, **params): ...
def _deprecate_api(old_name, new_name, api, next_version, type=...): ...
def _deprecate_class(old_name, new_class, next_version, instancecheck: bool = True): ...
def _is_iterable(obj): ...
def _is_path_like(path): ...
def _stringify_path(path): ...
def product(seq): ...
def get_contiguous_span(shape, strides, itemsize): ...
def find_free_port(): ...
def guid(): ...
def _break_traceback_cycle_from_frame(frame) -> None: ...
def _download_urllib(url, out_path) -> None: ...
def _download_requests(url, out_path) -> None: ...
def download_tzdata_on_windows() -> None: ...
