# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

from pyarrow._dataset import FileSystemDataset, InMemoryDataset, Scanner
from typing import Any
from collections.abc import Callable, Iterator

_DEPR_MSG: str

def doc(*docstrings, **params) -> Callable: ...
def _deprecate_api(
    old_name: str, new_name: str, api: Callable, next_version: str, type=...
) -> Callable: ...
def _deprecate_class(old_name, new_class, next_version, instancecheck: bool = True): ...
def _is_iterable(
    obj: FileSystemDataset | Iterator[Any] | InMemoryDataset | Scanner,
): ...
def _is_path_like(path) -> bool: ...
def _stringify_path(path) -> str: ...
def product(seq): ...
def get_contiguous_span(shape: tuple, strides: tuple, itemsize: int) -> int: ...
def find_free_port() -> int: ...
def guid() -> str: ...
def _break_traceback_cycle_from_frame(frame) -> None: ...
def _download_urllib(url, out_path) -> None: ...
def _download_requests(url, out_path) -> None: ...
def download_tzdata_on_windows() -> None: ...
