#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Generates python/pyarrow-stubs from the Cython and Python sources and checks
# the result against the nightly PyArrow wheel with mypy.stubtest.
# Run from the repository root. Requires uv, git and GNU sed.
set -euo pipefail

venv=python/.venv-stubgen
stubs=python/pyarrow-stubs

# MonkeyType does not support Python 3.14 yet.
[[ -d $venv ]] || uv venv --no-project --python 3.13 "$venv"
uv pip install --python "$venv/bin/python" --upgrade --prerelease allow \
    --default-index https://pypi.anaconda.org/scientific-python-nightly-wheels/simple \
    pyarrow
uv pip install --python "$venv/bin/python" --upgrade \
    'git+https://github.com/astral-sh/docstring-adder' stubgen-pyx 'mypy>=2.1' \
    'numpy>=2' cffi
# For scripts/add_types_to_stubs.py: tracing the test suite, scoring,
# formatting and linting.
uv pip install --python "$venv/bin/python" --upgrade \
    -r python/requirements-test.txt monkeytype pytest-xdist pyright ruff
# shellcheck source=/dev/null
source "$venv/bin/activate"

rm -rf "$stubs"
stubgen-pyx python/pyarrow --file '*.pyx' --include-private \
    --exclude-docstrings --output-dir "$stubs/pyarrow"

# Make the Cython stubs match what Python sees at runtime: drop special
# methods and C typedefs that have no Python counterpart, add the `mod`
# argument and reflected methods Cython gives operator slots, annotate
# unresolved names (private class attributes included, enum members excluded
# so they stay members), declare the `__slots__` attribute stubgen-pyx skips,
# and keep its provenance comment within the line length.
sed -E -i \
    -e '/^\s*def __(dealloc|getbuffer|releasebuffer|richcmp)__\(/d' \
    -e '/^\w+: TypeAlias = /d' \
    -e 's/^(\s*def __pow__\(self[^,)]*, [^,)]*)\)/\1, mod: None = None)/' \
    -e 's/^(\s*)def __(add|sub|mul|matmul|truediv|floordiv|mod|divmod|pow|lshift|rshift|and|or|xor)__\((self[^)]*)\)(.*)$/&\n\1def __r\2__(\3)\4/' \
    -e 's/^(\w+|\s+_\w*) = \.\.\.$/\1: Incomplete/' \
    -e '1a from _typeshed import Incomplete' \
    -e '/^class TracingServerMiddleware\(/a\    trace_context: Incomplete' \
    -e 's/^# This file was generated by stubgen-pyx v[0-9.]+ from /# Generated by stubgen-pyx from /' \
    "$stubs"/pyarrow/*.pyi
# Symbols stubgen-pyx cannot derive from the sources: chained and try/except
# guarded module assignments.
cat >> "$stubs/pyarrow/lib.pyi" <<'PYI'

_NULL: NullScalar
NA: NullScalar
PYI
cat >> "$stubs/pyarrow/_dataset_parquet.pyi" <<'PYI'

parquet_encryption_enabled: bool
PYI
cat >> "$stubs/pyarrow/_substrait.pyi" <<'PYI'

from types import ModuleType
py_substrait: ModuleType | None
PYI

# Python modules are parsed, not imported, so optional dependencies are not
# needed. pyarrow.compute builds its functions at import time and is inspected.
stubgen --no-import --include-private --search-path python --output "$stubs" \
    -m pyarrow -m pyarrow._compute_docstrings -m pyarrow.acero \
    -m pyarrow.benchmark -m pyarrow.cffi -m pyarrow.csv -m pyarrow.cuda \
    -m pyarrow.dataset -m pyarrow.feather -m pyarrow.flight -m pyarrow.fs \
    -m pyarrow.ipc -m pyarrow.json -m pyarrow.jvm -m pyarrow.orc \
    -m pyarrow.pandas_compat -m pyarrow.substrait -m pyarrow.types \
    -m pyarrow.util -m pyarrow.interchange -m pyarrow.interchange.buffer \
    -m pyarrow.interchange.column -m pyarrow.interchange.dataframe \
    -m pyarrow.interchange.from_dataframe -m pyarrow.parquet \
    -m pyarrow.parquet.core -m pyarrow.parquet.encryption
stubgen --inspect-mode --module pyarrow.compute --output "$stubs"
# mypy stubgen drops imports of private names and variables outside __all__.
echo 'from pyarrow.lib import _NULL as NULL' >> "$stubs/pyarrow/__init__.pyi"
echo 'EXCLUDED_PARQUET_PATHS: set[str]' >> "$stubs/pyarrow/parquet/core.pyi"
#add-docstrings --packages "$stubs/pyarrow"

# Reuse this script's license header.
header=$(sed -n '/^# Licensed to the Apache/,/^# under the License\.$/p' "$0")
for stub in "$stubs"/pyarrow/*.pyi "$stubs"/pyarrow/*/*.pyi; do
    { echo "$header"; echo; cat "$stub"; } > "$stub.tmp"
    mv "$stub.tmp" "$stub"
done

# Mismatches the stubs cannot express, as regexes over dotted runtime paths:
# attributes Cython adds to every module and class; cdef-class __init__ and
# __call__, which Cython exposes as (*args, **kwargs); the shipped test suite,
# vendored modules (mypy stubgen refuses them), bundled shared libraries and
# extension modules missing from the nightly wheel; names that are not
# identifiers or depend on optional imports; stubgen quirks. Entries go unused
# when the wheel includes more optional modules, which is fine.
allowlist=$(mktemp)
cat > "$allowlist" <<'TXT'
.*\.__(reduce_cython|setstate_cython|test|pyx_capi)__
pyarrow\.(lib|gandiva|_\w+)\.\w+\.__(init|call)__
pyarrow\.(tests|vendored)(\..*)?
pyarrow\.(conftest|_?cuda|gandiva)
pyarrow\.libarrow_python(_\w+)?
pyarrow\.compute\.(and|or)
pyarrow\.compute\._OptionsClassDoc(\..*)?
pyarrow\.parse_git
pyarrow\.acero\.(ds|DatasetModuleStub)
pyarrow\._compute\.SUPPORTED_INPUT_ARR_TYPES
pyarrow\.types\._INTEGER_TYPES
pyarrow\._dataset\.TaggedRecordBatch@base1
pyarrow\.parquet\.core\.__all__
pyarrow\._orc\.WriteOptions
TXT
# Check runtime coverage only; mypy build errors in the generated stubs would
# otherwise abort stubtest.
mypy_config=$(mktemp)
cat > "$mypy_config" <<'INI'
[mypy]

[mypy-pyarrow.*]
ignore_errors = True
INI

MYPYPATH=$PWD/$stubs python -m mypy.stubtest pyarrow --concise \
    --ignore-positional-only --ignore-disjoint-bases \
    --allowlist "$allowlist" --ignore-unused-allowlist \
    --mypy-config-file "$mypy_config"

# Report how many public runtime symbols (module attributes and class members
# defined in each module) the stubs declare, and list the ones they miss.
python - "$stubs" <<'PY'
import ast, importlib, pkgutil, sys, types
import pyarrow

stubs = sys.argv[1]

def declared(node):
    names = set()
    for child in node.body:
        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.add(child.name)
        elif isinstance(child, ast.AnnAssign):
            names.add(child.target.id)
        elif isinstance(child, ast.Assign):
            names.update(t.id for t in child.targets if isinstance(t, ast.Name))
        elif isinstance(child, ast.ImportFrom):
            names.update(a.asname or a.name for a in child.names)
        if isinstance(child, ast.ClassDef):
            names.update(f"{child.name}.{n}" for n in declared(child))
    return names

def public(namespace, module_name):
    return {n for n, v in vars(namespace).items()
            if not n.startswith("_") and not isinstance(v, types.ModuleType)
            and getattr(v, "__module__", module_name) == module_name}

total = covered = 0
modules = ["pyarrow"] + [m.name for m in pkgutil.walk_packages(pyarrow.__path__, "pyarrow.")]
for name in modules:
    if name.startswith(("pyarrow.tests", "pyarrow.vendored")) or name.endswith("conftest"):
        continue
    try:
        module = importlib.import_module(name)
    except ImportError:
        continue
    symbols = set()
    for attr in public(module, name):
        symbols.add(attr)
        obj = getattr(module, attr)
        if isinstance(obj, type):
            symbols.update(f"{attr}.{m}" for m in vars(obj) if not m.startswith("_"))
    path = f"{stubs}/{name.replace('.', '/')}"
    path += "/__init__.pyi" if hasattr(module, "__path__") else ".pyi"
    try:
        stub = declared(ast.parse(open(path).read()))
    except FileNotFoundError:
        stub = set()
    missing = sorted(symbols - stub)
    total += len(symbols)
    covered += len(symbols) - len(missing)
    print(f"{name}: {len(symbols) - len(missing)}/{len(symbols)}", *missing)
print(f"Stub coverage: {covered}/{total} public symbols ({100 * covered // max(total, 1)}%)")
PY
