import types
from _typeshed import Incomplete
from pyarrow._parquet import ColumnChunkMetaData as ColumnChunkMetaData, ColumnSchema as ColumnSchema, FileDecryptionProperties as FileDecryptionProperties, FileEncryptionProperties as FileEncryptionProperties, FileMetaData as FileMetaData, ParquetLogicalType as ParquetLogicalType, ParquetReader as ParquetReader, ParquetSchema as ParquetSchema, RowGroupMetaData as RowGroupMetaData, SortingColumn as SortingColumn, Statistics as Statistics

__all__ = ['ParquetReader', 'Statistics', 'FileMetaData', 'RowGroupMetaData', 'ColumnChunkMetaData', 'ParquetSchema', 'ColumnSchema', 'ParquetLogicalType', 'FileEncryptionProperties', 'FileDecryptionProperties', 'SortingColumn', 'filters_to_expression', '_filters_to_expression', 'ParquetFile', 'ParquetWriter', 'ParquetDataset', 'read_table', 'read_pandas', 'write_table', 'write_to_dataset', 'write_metadata', 'read_metadata', 'read_schema']

def filters_to_expression(filters): ...

_filters_to_expression: Incomplete

class ParquetFile:
    _close_source: Incomplete
    reader: Incomplete
    common_metadata: Incomplete
    _nested_paths_by_prefix: Incomplete
    def __init__(self, source, *, metadata=None, common_metadata=None, read_dictionary=None, binary_type=None, list_type=None, memory_map: bool = False, buffer_size: int = 0, pre_buffer: bool = True, coerce_int96_timestamp_unit=None, decryption_properties=None, thrift_string_size_limit=None, thrift_container_size_limit=None, schema_depth_limit=None, filesystem=None, page_checksum_verification: bool = False, arrow_extensions_enabled: bool = True) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *args, **kwargs) -> None: ...
    def _build_nested_paths(self): ...
    @property
    def metadata(self): ...
    @property
    def schema(self): ...
    @property
    def schema_arrow(self): ...
    @property
    def num_row_groups(self): ...
    def close(self, force: bool = False): ...
    @property
    def closed(self) -> bool: ...
    def read_row_group(self, i, columns=None, use_threads: bool = True, use_pandas_metadata: bool = False): ...
    def read_row_groups(self, row_groups, columns=None, use_threads: bool = True, use_pandas_metadata: bool = False): ...
    def iter_batches(self, batch_size: int = 65536, row_groups=None, columns=None, use_threads: bool = True, use_pandas_metadata: bool = False): ...
    def read(self, columns=None, use_threads: bool = True, use_pandas_metadata: bool = False): ...
    def scan_contents(self, columns=None, batch_size: int = 65536): ...
    def _get_column_indices(self, column_names, use_pandas_metadata: bool = False): ...

class ParquetWriter:
    __doc__: Incomplete
    flavor: Incomplete
    schema_changed: bool
    schema: Incomplete
    where: Incomplete
    file_handle: Incomplete
    _metadata_collector: Incomplete
    writer: Incomplete
    is_open: bool
    def __init__(self, where, schema, filesystem=None, flavor=None, version: str = '2.6', use_dictionary: bool = True, compression: str = 'snappy', write_statistics: bool = True, use_deprecated_int96_timestamps=None, compression_level=None, use_byte_stream_split: bool = False, column_encoding=None, writer_engine_version=None, data_page_version: str = '1.0', use_compliant_nested_type: bool = True, encryption_properties=None, write_batch_size=None, dictionary_pagesize_limit=None, store_schema: bool = True, write_page_index: bool = False, write_page_checksum: bool = False, sorting_columns=None, store_decimal_as_integer: bool = False, write_time_adjusted_to_utc: bool = False, max_rows_per_page=None, bloom_filter_options=None, use_content_defined_chunking: bool = False, **options) -> None: ...
    def __del__(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *args, **kwargs): ...
    def write(self, table_or_batch, row_group_size=None) -> None: ...
    def write_batch(self, batch, row_group_size=None) -> None: ...
    def write_table(self, table, row_group_size=None) -> None: ...
    def close(self) -> None: ...
    def add_key_value_metadata(self, key_value_metadata) -> None: ...

class ParquetDataset:
    __doc__: Incomplete
    _filter_expression: Incomplete
    _base_dir: Incomplete
    _dataset: Incomplete
    def __init__(self, path_or_paths, filesystem=None, schema=None, *, filters=None, read_dictionary=None, binary_type=None, list_type=None, memory_map: bool = False, buffer_size=None, partitioning: str = 'hive', ignore_prefixes=None, pre_buffer: bool = True, coerce_int96_timestamp_unit=None, decryption_properties=None, thrift_string_size_limit=None, thrift_container_size_limit=None, schema_depth_limit=None, page_checksum_verification: bool = False, arrow_extensions_enabled: bool = True) -> None: ...
    def equals(self, other): ...
    def __eq__(self, other): ...
    @property
    def schema(self): ...
    def read(self, columns=None, use_threads: bool = True, use_pandas_metadata: bool = False): ...
    def _get_common_pandas_metadata(self): ...
    def read_pandas(self, **kwargs): ...
    @property
    def fragments(self): ...
    @property
    def files(self): ...
    @property
    def filesystem(self): ...
    @property
    def partitioning(self): ...

def read_table(source, *, columns=None, use_threads: bool = True, schema=None, use_pandas_metadata: bool = False, read_dictionary=None, binary_type=None, list_type=None, memory_map: bool = False, buffer_size: int = 0, partitioning: str = 'hive', filesystem=None, filters=None, ignore_prefixes=None, pre_buffer: bool = True, coerce_int96_timestamp_unit=None, decryption_properties=None, thrift_string_size_limit=None, thrift_container_size_limit=None, schema_depth_limit=None, page_checksum_verification: bool = False, arrow_extensions_enabled: bool = True): ...
def read_pandas(source, columns=None, **kwargs): ...
def write_table(table, where, row_group_size=None, version: str = '2.6', use_dictionary: bool = True, compression: str = 'snappy', write_statistics: bool = True, use_deprecated_int96_timestamps=None, coerce_timestamps=None, allow_truncated_timestamps: bool = False, data_page_size=None, flavor=None, filesystem=None, compression_level=None, use_byte_stream_split: bool = False, column_encoding=None, data_page_version: str = '1.0', use_compliant_nested_type: bool = True, encryption_properties=None, write_batch_size=None, dictionary_pagesize_limit=None, store_schema: bool = True, write_page_index: bool = False, write_page_checksum: bool = False, sorting_columns=None, store_decimal_as_integer: bool = False, write_time_adjusted_to_utc: bool = False, max_rows_per_page=None, bloom_filter_options=None, use_content_defined_chunking: bool = False, **kwargs) -> None: ...
def write_to_dataset(table, root_path, partition_cols=None, filesystem=None, schema=None, partitioning=None, basename_template=None, use_threads=None, file_visitor=None, existing_data_behavior=None, **kwargs) -> None: ...
def write_metadata(schema, where, metadata_collector=None, filesystem=None, **kwargs) -> None: ...
def read_metadata(where, memory_map: bool = False, decryption_properties=None, filesystem=None, arrow_extensions_enabled: bool = True): ...
def read_schema(where, memory_map: bool = False, decryption_properties=None, filesystem=None, arrow_extensions_enabled: bool = True): ...
EXCLUDED_PARQUET_PATHS: set[str]
